#!/usr/bin/env elixir
# Grep Porffor builtins/codegen for todo/not-implemented markers → conformance/capabilities.work appendix.
Mix.Task.run("app.start")

root = Path.join([File.cwd!(), "compilers", "js", "porffor"])
patterns = ~w(todo: not implemented not spec compliant FIXME)
paths = [
  Path.join(root, "compiler/codegen.js"),
  Path.join(root, "compiler/builtins")
]

lines =
  for dir <- paths, File.exists?(dir) do
    files = if File.dir?(dir), do: Path.wildcard(Path.join(dir, "**/*.{js,ts}")), else: [dir]

    for file <- files,
        line <- File.read!(file) |> String.split("\n"),
        Enum.any?(patterns, &String.contains?(String.downcase(line), &1)) do
      {Path.relative_to(file, root), String.trim(line)}
    end
  end
  |> List.flatten()
  |> Enum.uniq()
  |> Enum.take(200)

out = Path.join([File.cwd!(), "conformance", "capabilities.work"])
appendix = """
audit :codegen_todos do
  note "auto-generated by tools/gen_capability_matrix.exs — #{length(lines)} markers"
#{for {file, line} <- lines, do: "  marker #{inspect(file)}, text: #{inspect(String.slice(line, 0, 120))}"}
end
"""

if File.regular?(out) do
  base = File.read!(out) |> String.split("audit :codegen_todos") |> hd()
  File.write!(out, base <> appendix)
else
  File.write!(out, appendix)
end

IO.puts("updated #{out} with #{length(lines)} todo markers")
