// brandnana skill — install / show / update the Brandnana Claude skill.
//
// Targets:
//   claude-code  → ~/.claude/skills/brandnana/SKILL.md
//   codex        → ~/.codex/instructions/brandnana.md
//                  (Codex CLI reads ~/.codex/instructions/*.md as global agent
//                  instructions; there is no per-skill registry in the OSS
//                  openai/codex repo as of 2026-05. The closest analogue is
//                  the instructions dir. Source: https://github.com/openai/codex
//                  — absent a dedicated skill slot we append there rather than
//                  inventing a convention.)
//   cursor       → .cursor/rules/brandnana.mdc  (in cwd; Cursor reads .mdc
//                  rule files from the .cursor/rules/ dir. Content is prefixed
//                  with YAML frontmatter so Cursor can categorise the rule.)
//   stdout       → write to stdout, no file IO.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Command } from "commander";
import { emit, runAction, say } from "../output.js";

// ---------------------------------------------------------------------------
// Skill source resolution
// ---------------------------------------------------------------------------

/** Absolute path to packages/skill/ relative to this binary at runtime.
 *
 *  Directory layout when running from source:
 *    apps/cli/src/commands/skill.ts  → ../../../../packages/skill/SKILL.md
 *
 *  When built to dist/:
 *    apps/cli/dist/index.js (single bundle) — __dirname is apps/cli/dist
 *    → ../../../packages/skill/SKILL.md
 *
 *  We try the source path first (import.meta.url), then fall back to the
 *  compiled-bundle path relative to process.execPath.
 */
function skillPackageDir(): string {
  // import.meta.url works in both Bun (source) and the ESM bundle.
  const thisFile = fileURLToPath(import.meta.url);
  // src/commands/skill.ts  → ../../.. = apps/cli  → ../../../../packages/skill
  const fromSrc = resolve(dirname(thisFile), "..", "..", "..", "..", "packages", "skill");
  // dist/index.js          → ..     = apps/cli  → ../../packages/skill
  const fromDist = resolve(dirname(thisFile), "..", "..", "..", "packages", "skill");
  // Return whichever one contains SKILL.md. Default to fromSrc if neither
  // resolves at check-time (caller will surface the error when reading).
  return fromSrc; // bun build bundles everything into one file at dist/index.js
}

async function readSkillFile(name = "SKILL.md"): Promise<string> {
  const path = join(skillPackageDir(), name);
  return readFile(path, "utf8");
}

// ---------------------------------------------------------------------------
// Target definitions
// ---------------------------------------------------------------------------

type Target = "claude-code" | "codex" | "cursor" | "stdout";

const VALID_TARGETS: Target[] = ["claude-code", "codex", "cursor", "stdout"];

function targetPath(target: Target): string | null {
  switch (target) {
    case "claude-code":
      return join(homedir(), ".claude", "skills", "brandnana", "SKILL.md");
    case "codex":
      // Codex CLI (~/.codex/instructions/) — closest to a global skill slot.
      return join(homedir(), ".codex", "instructions", "brandnana.md");
    case "cursor":
      // Cursor reads .cursor/rules/*.mdc from the project root.
      return resolve(process.cwd(), ".cursor", "rules", "brandnana.mdc");
    case "stdout":
      return null;
  }
}

function wrapForTarget(target: Target, raw: string): string {
  if (target === "cursor") {
    // Cursor rule files require YAML frontmatter. The body is the rule content.
    // alwaysApply: false means Cursor only applies it when the user invokes it
    // or when the agent selects it for context.
    return [
      "---",
      "name: brandnana",
      'globs: ["**/*"]',
      "alwaysApply: false",
      "---",
      "<!--",
      "  This file was generated by `brandnana skill install --target cursor`.",
      "  Source: @brandnana/skill — do not edit by hand; re-run the command to update.",
      "-->",
      "",
      raw,
    ].join("\n");
  }
  if (target === "codex") {
    // Prepend a brief header so the instructions file is self-describing.
    return [
      "<!-- Generated by `brandnana skill install --target codex`. Re-run to update. -->",
      "",
      raw,
    ].join("\n");
  }
  // claude-code / stdout: emit as-is (already has YAML frontmatter from SKILL.md).
  return raw;
}

// ---------------------------------------------------------------------------
// Command registration
// ---------------------------------------------------------------------------

export function registerSkill(program: Command): void {
  const skill = program.command("skill").description("Manage the Brandnana AI-harness skill");

  // ── install ──────────────────────────────────────────────────────────────
  skill
    .command("install")
    .description("Install the Brandnana skill into an AI harness config directory")
    .requiredOption(
      "--target <name>",
      `Target harness: ${VALID_TARGETS.join(" | ")}`,
    )
    .option("--dry-run", "Show target path + content size without writing", false)
    .action(
      (opts: { target: string; dryRun: boolean }) =>
        runAction(async () => {
          const target = opts.target as Target;
          if (!VALID_TARGETS.includes(target)) {
            throw new Error(
              `Unknown target "${target}". Valid targets: ${VALID_TARGETS.join(", ")}`,
            );
          }

          const raw = await readSkillFile("SKILL.md");
          const content = wrapForTarget(target, raw);

          if (target === "stdout") {
            process.stdout.write(content);
            return;
          }

          const outPath = targetPath(target) as string;

          if (opts.dryRun) {
            emit(
              { target, path: outPath, bytes: Buffer.byteLength(content, "utf8") },
              `dry-run: would write ${Buffer.byteLength(content, "utf8")} bytes → ${outPath}`,
            );
            return;
          }

          await mkdir(dirname(outPath), { recursive: true });
          await writeFile(outPath, content, "utf8");
          emit(
            { target, path: outPath, bytes: Buffer.byteLength(content, "utf8") },
            `skill installed → ${outPath}`,
          );
        }),
    );

  // ── show ─────────────────────────────────────────────────────────────────
  skill
    .command("show")
    .description("Print SKILL.md to stdout")
    .action(() =>
      runAction(async () => {
        const content = await readSkillFile("SKILL.md");
        process.stdout.write(content);
      }),
    );

  // ── update ───────────────────────────────────────────────────────────────
  skill
    .command("update")
    .description("Re-install the skill for all targets that already have a file present")
    .option("--dry-run", "Show what would be updated without writing", false)
    .action(
      (opts: { dryRun: boolean }) =>
        runAction(async () => {
          const raw = await readSkillFile("SKILL.md");
          const written: string[] = [];

          for (const target of VALID_TARGETS) {
            if (target === "stdout") continue;
            const outPath = targetPath(target) as string;
            // Only update targets that are already installed.
            let exists = false;
            try {
              await readFile(outPath);
              exists = true;
            } catch {
              // not installed — skip
            }
            if (!exists) continue;

            const content = wrapForTarget(target, raw);
            if (!opts.dryRun) {
              await writeFile(outPath, content, "utf8");
            }
            written.push(outPath);
            say(`${opts.dryRun ? "would update" : "updated"}: ${outPath}`);
          }

          if (written.length === 0) {
            say("no installed skill targets found — run `brandnana skill install --target <name>` first");
          }

          emit(
            { updated: written, dryRun: opts.dryRun },
            `${opts.dryRun ? "dry-run: " : ""}${written.length} target(s) updated`,
          );
        }),
    );
}
