#!/bin/sh
# Nexus container entrypoint — durability wrapper around the release.
#
# When an object-store replica is injected (WB_S3_* secrets), the tenant SQLite on the volume is
# replicated off-box by Litestream: on a new/replaced machine we restore the last shipped frame
# BEFORE boot, then run the release wrapped in continuous replication. With no S3 secrets the nexus
# runs SQLite-on-volume unreplicated (still durable on the mounted volume). The litestream config is
# generated by the runtime from Nexus.Secrets (single source of truth); object keys reach litestream
# via LITESTREAM_* env and are never written to disk.
set -e

DB="${WB_DATA:-/data}/.nexus/nexus.db"
CFG="/etc/litestream.yml"

# Accept our canonical WB_S3_* names OR the standard ones `fly storage create` (Tigris) sets.
S3_BUCKET="${WB_S3_BUCKET:-${BUCKET_NAME:-}}"
S3_AKID="${WB_S3_ACCESS_KEY_ID:-${AWS_ACCESS_KEY_ID:-}}"
S3_SECRET="${WB_S3_SECRET_ACCESS_KEY:-${AWS_SECRET_ACCESS_KEY:-}}"

if [ -n "$S3_BUCKET" ] && [ -n "$S3_AKID" ] && command -v litestream >/dev/null 2>&1; then
  export LITESTREAM_ACCESS_KEY_ID="$S3_AKID"
  export LITESTREAM_SECRET_ACCESS_KEY="$S3_SECRET"
  echo "[entrypoint] litestream enabled → generating config from injected secrets"
  mkdir -p "$(dirname "$DB")"
  bin/nexus eval 'Nexus.Litestream.write_config()'
  echo "[entrypoint] restoring $DB from replica if the volume is empty"
  litestream restore -if-db-not-exists -if-replica-exists -config "$CFG" "$DB" || true
  echo "[entrypoint] starting nexus under continuous replication"
  exec litestream replicate -config "$CFG" -exec "bin/nexus start"
else
  echo "[entrypoint] no object-store replica configured → SQLite-on-volume, unreplicated"
  exec bin/nexus start
fi
