// Single source of truth for the brandnana verb catalog.
// Every verb that ships across the API, CLI, and agent surfaces is listed here.
// Adding a new verb means adding one entry in VERBS.

export interface VerbInput {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

export interface Verb {
  id: string;
  httpMethod: "GET" | "POST";
  httpPath: string;
  cliCommand: string[];
  summary: string;
  description: string;
  inputs: VerbInput[];
  outputs: string;
  vendors?: string[];
}

export const VERBS: Verb[] = [
  // ── Auth ──────────────────────────────────────────────────────────────────

  {
    id: "auth.login",
    httpMethod: "GET",
    httpPath: "/auth/cli/config",
    cliCommand: ["login"],
    summary: "Sign in via GitHub device flow; stores API key in OS keychain",
    description:
      "Fetches /auth/cli/config (OAuth client id), runs the GitHub device flow, then POSTs the GitHub token to /auth/cli/exchange to mint a brandnana API key. The key is stored in the OS keychain.",
    inputs: [],
    outputs: "API key prefix + stored storage location",
  },
  {
    id: "auth.whoami",
    httpMethod: "GET",
    httpPath: "/whoami",
    cliCommand: ["whoami"],
    summary: "Show the user behind the current API key",
    description: "Returns { user: { id, github_login, email } } for the bearer token in use.",
    inputs: [],
    outputs: "{ user: { id, github_login, email } }",
  },
  {
    id: "auth.connect.meta",
    httpMethod: "POST",
    httpPath: "/auth/meta",
    cliCommand: ["auth", "meta"],
    summary: "Connect a Meta account for ad-library access",
    description:
      "Initiates the Meta OAuth session. The CLI opens the browser URL, polls for connection state, and emits a connected event when the user authorizes.",
    inputs: [],
    outputs: "{ provider, state, session_id }",
    vendors: ["meta"],
  },
  {
    id: "auth.connect.tiktok",
    httpMethod: "POST",
    httpPath: "/auth/meta",
    cliCommand: ["auth", "tiktok"],
    summary: "Connect a TikTok account for ad-library access",
    description: "Initiates the TikTok OAuth session. Same flow as auth.connect.meta.",
    inputs: [],
    outputs: "{ provider, state, session_id }",
    vendors: ["tiktok"],
  },
  {
    id: "auth.connect.google",
    httpMethod: "POST",
    httpPath: "/auth/meta",
    cliCommand: ["auth", "google"],
    summary: "Connect a Google account for ad-library access",
    description: "Initiates the Google OAuth session. Same flow as auth.connect.meta.",
    inputs: [],
    outputs: "{ provider, state, session_id }",
    vendors: ["google"],
  },
  {
    id: "auth.status",
    httpMethod: "GET",
    httpPath: "/auth/meta",
    cliCommand: ["auth", "status"],
    summary: "Show connected ad-library providers",
    description: "Lists all OAuth-connected providers for the current user.",
    inputs: [],
    outputs: "Array of { provider, state }",
  },

  // ── Brand ─────────────────────────────────────────────────────────────────

  {
    id: "brand.fetch",
    httpMethod: "GET",
    httpPath: "/brand/:domain",
    cliCommand: ["brand", "fetch"],
    summary: "Fetch logo, palette, fonts, screenshot, styleguide for a brand",
    description:
      "Wraps context.dev /brand/retrieve, normalises into the Brand shape, and returns it. The CLI writes the core record to local SQLite. Optional ?include=fonts,screenshot,styleguide fans out to side-quests concurrently.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain (e.g. nike.com)" },
      {
        name: "include",
        type: "string",
        required: false,
        description: "Comma-separated extras: fonts, screenshot, styleguide, all",
      },
    ],
    outputs: "{ brand: NormalisedBrand, extras?: { fonts, screenshot_url, styleguide } }",
    vendors: ["context-dev"],
  },
  {
    id: "brand.fonts",
    httpMethod: "GET",
    httpPath: "/brand/:domain/fonts",
    cliCommand: ["brand", "fonts"],
    summary: "Extract web fonts from a brand's homepage",
    description:
      "Returns font families, fallbacks, usage stats, and CSS URL per font. Parses @font-face, Google Fonts, and Adobe Typekit. Falls back to the managed API on WAF-blocked sites.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
    ],
    outputs: "{ fonts: BrandFont[] }",
    vendors: ["context-dev"],
  },
  {
    id: "brand.styleguide",
    httpMethod: "GET",
    httpPath: "/brand/:domain/styleguide",
    cliCommand: ["brand", "styleguide"],
    summary: "Fetch brand styleguide: colors, typography, components",
    description: "Returns context.dev's styleguide payload (mode, typography, components).",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
    ],
    outputs: "{ styleguide: { mode, typography, components } }",
    vendors: ["context-dev"],
  },
  {
    id: "brand.product",
    httpMethod: "GET",
    httpPath: "/brand/:domain/product",
    cliCommand: ["brand", "product"],
    summary: "Extract a single product page (name, price, images, features)",
    description:
      "The director uses this to pull product imagery and copy for hero shots or overlays. Requires the product URL as a query parameter.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
      { name: "url", type: "string", required: true, description: "Product page URL (https://…)" },
    ],
    outputs: "{ product: { name, price, images, features } }",
    vendors: ["context-dev"],
  },
  {
    id: "brand.screenshot",
    httpMethod: "GET",
    httpPath: "/brand/:domain/screenshot",
    cliCommand: ["brand", "screenshot"],
    summary: "Viewport screenshot URL for a brand's homepage",
    description: "Returns a screenshot URL hosted by context.dev.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
    ],
    outputs: "{ screenshot: string | null }",
    vendors: ["context-dev"],
  },
  {
    id: "brand.company",
    httpMethod: "GET",
    httpPath: "/brand/:domain/company",
    cliCommand: ["brand", "company"],
    summary: "Firmographics for a brand (industry, employee range, location, socials, NAICS/SIC)",
    description:
      "Wraps The Companies API (thecompaniesapi.com) /companies/{domain} and normalises into a Company shape.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
    ],
    outputs: "{ company }",
    vendors: ["the-companies-api"],
  },

  // ── Logo ──────────────────────────────────────────────────────────────────

  {
    id: "logo.find",
    httpMethod: "GET",
    httpPath: "/brand/:domain",
    cliCommand: ["logo"],
    summary: "Return real brand-accurate logos from multiple sources",
    description:
      "Probes in parallel (5s timeout each): homepage scrape, Wikipedia Commons (SVG), brandfetch.com, logo.dev, simpleicons.org. Rejects favicons and app-icon-shaped (square) candidates. Falls back to managed API on WAF block.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
      {
        name: "skipSimpleIcons",
        type: "boolean",
        required: false,
        description: "Skip simpleicons.org even if no other SVG was found",
      },
    ],
    outputs: "{ candidates: LogoCandidate[], recommended: number, rejected: RejectedCandidate[] }",
    vendors: ["context-dev"],
  },

  // ── Ads ───────────────────────────────────────────────────────────────────

  {
    id: "ads.search",
    httpMethod: "POST",
    httpPath: "/ads/search",
    cliCommand: ["ads", "search"],
    summary: "ScrapeCreators ad-library fan-out (Meta + Google + LinkedIn) by source; writes into local ads table",
    description:
      "Fans out across ScrapeCreators ad libraries by source (meta → Meta Ad Library, google → Google Ads Transparency, linkedin → LinkedIn Ad Library, all → every leg in parallel), normalises results into the Ad shape, de-duplicates by external_id, and caps at limit. Each leg reports availability and result counts via warnings[]; an unavailable leg (missing key/approval) is never silently swallowed.",
    inputs: [
      { name: "query", type: "string", required: true, description: "Search query" },
      {
        name: "source",
        type: "'meta'|'google'|'linkedin'|'all'",
        required: false,
        description: "Ad source to search (default: all)",
      },
      { name: "limit", type: "number", required: false, description: "Max results (1–100, default 20)" },
      {
        name: "brand",
        type: "string",
        required: false,
        description: "Brand domain to scope Meta ad-library lookup",
      },
    ],
    outputs: "{ query, source, count, ads: NormalisedAd[], warnings: string[] }",
    vendors: ["scrapecreators"],
  },
  {
    id: "ads.sync",
    httpMethod: "POST",
    httpPath: "/ads/meta",
    cliCommand: ["ads", "sync"],
    summary: "Pull ads from a connected ad-library into the local SQLite",
    description:
      "Reads all ad accounts visible to the stored Meta token, fetches ads for each, and upserts into the local ads table. Only --source=meta is implemented today.",
    inputs: [
      {
        name: "source",
        type: "'meta'",
        required: false,
        description: "Ad source (only meta today)",
      },
      {
        name: "adAccountId",
        type: "string",
        required: false,
        description: "Specific Meta ad account. Omit to sync all.",
      },
      { name: "limit", type: "number", required: false, description: "Max ads per account (default 50)" },
    ],
    outputs: "{ source, accounts, ads, db }",
    vendors: ["meta"],
  },
  {
    id: "ads.meta.accounts",
    httpMethod: "GET",
    httpPath: "/ads/meta/accounts",
    cliCommand: ["ads", "meta", "accounts"],
    summary: "List Meta ad accounts visible to the stored token",
    description: "Returns all ad accounts the META_GRAPH_TOKEN can see.",
    inputs: [],
    outputs: "{ accounts: AdAccount[] }",
    vendors: ["meta"],
  },
  {
    id: "ads.meta.library",
    httpMethod: "POST",
    httpPath: "/ads/meta/library",
    cliCommand: ["ads", "meta", "library"],
    summary: "Search the Meta Ad Library (requires approved API access)",
    description:
      "Returns 503 with actionable guidance until Meta Ad Library API is approved. When approved, returns paginated ad creatives from the official Meta Ad Library API.",
    inputs: [
      { name: "query", type: "string", required: true, description: "Search query" },
      { name: "countries", type: "string[]", required: false, description: "Country codes" },
      { name: "limit", type: "number", required: false, description: "Max results" },
    ],
    outputs: "{ source, count, ads }",
    vendors: ["meta"],
  },
  {
    id: "ads.google",
    httpMethod: "POST",
    httpPath: "/ads/google",
    cliCommand: ["ads", "google"],
    summary: "Scrape the Google Ads Transparency Center for an advertiser",
    description:
      "Returns advertiser_id, advertiser_url, and creative ids extracted from the rendered transparency page.",
    inputs: [
      { name: "brand", type: "string", required: false, description: "Brand name" },
      {
        name: "advertiser_url",
        type: "string",
        required: false,
        description: "Direct advertiser URL",
      },
    ],
    outputs: "{ advertiser_id, advertiser_url, creative_ids }",
    vendors: ["google"],
  },

  // ── Catalog ───────────────────────────────────────────────────────────────

  {
    id: "catalog.crawl",
    httpMethod: "POST",
    httpPath: "/catalog/crawl",
    cliCommand: ["catalog", "crawl"],
    summary: "Crawl every product from a brand's site into local SQLite",
    description:
      "Dispatches to the best strategy: auto (shopify → context-dev), shopify (/products.json walker), context-dev (12-product cap), sitemap (robots.txt + JSON-LD), or llm (Firecrawl + OpenRouter). Streams NDJSON rows. The SDK client.catalog.crawl() consumes this stream.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
      {
        name: "strategy",
        type: "'auto'|'shopify'|'context-dev'|'sitemap'|'llm'",
        required: false,
        description: "Crawl strategy (default: auto)",
      },
      { name: "brand_id", type: "string", required: false, description: "Brand UUID (FK into brands)" },
      { name: "max_urls", type: "number", required: false, description: "Cap for sitemap/llm crawl" },
      {
        name: "force",
        type: "boolean",
        required: false,
        description: "Override in-flight crawl dedup guard",
      },
    ],
    outputs: "NDJSON stream of CatalogRow ({ __type: 'product' | 'product_image' | 'stats' })",
    vendors: ["context-dev", "openrouter"],
  },
  {
    id: "catalog.status",
    httpMethod: "GET",
    httpPath: "/catalog/status/:domain",
    cliCommand: ["catalog", "status"],
    summary: "Current crawl state for a domain",
    description: "Returns Durable Object crawl state for (tenant, domain). Returns { status: 'idle' } if no crawl has run.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
    ],
    outputs: "{ domain, state: CrawlState }",
  },

  // ── Brief ─────────────────────────────────────────────────────────────────

  {
    id: "brief.get",
    httpMethod: "GET",
    httpPath: "/brief/:domain",
    cliCommand: ["brief"],
    summary: "One-shot cross-channel brand brief: brand + social + ads",
    description:
      "Server-side fan-out across 9 calls (brand, Instagram, TikTok, YouTube, Twitter, Facebook, Linktree, Meta ads, Google ads). Each leg is best-effort; failures land in errors[] and the rest still emits. Saves 8 round-trips vs calling each endpoint separately.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
      {
        name: "handle",
        type: "string",
        required: false,
        description: "Social handle (defaults to second-level domain)",
      },
    ],
    outputs: "BriefResult { brand, design, social: { instagram, tiktok, youtube, twitter, facebook, linktree }, ads: { meta, google }, errors }",
    vendors: ["context-dev", "meta", "scrapecreators", "google"],
  },

  // ── Design ────────────────────────────────────────────────────────────────

  {
    id: "design.tokens",
    httpMethod: "GET",
    httpPath: "/design/tokens/:domain",
    cliCommand: ["design", "tokens"],
    summary: "Fetch normalised design tokens (palette, fonts, voice) for a brand",
    description:
      "Fires brand, styleguide, and fonts in parallel. Returns a flat, agent-friendly DesignTokens shape (W3C-adjacent). v1 returns null for radii, spacing_rhythm, gradients — those require a Browser Rendering pass.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain" },
    ],
    outputs: "DesignTokens { domain, palette, fonts, voice, radii: null, spacing_rhythm: null, gradients: null, sources }",
    vendors: ["context-dev"],
  },

  // ── Resolve ───────────────────────────────────────────────────────────────

  {
    id: "resolve.query",
    httpMethod: "POST",
    httpPath: "/v1/resolve",
    cliCommand: ["resolve"],
    summary: "Find the canonical domain for an ambiguous brand reference",
    description:
      "Probes four sources in parallel with 5s caps each: direct-guess (common domain patterns + HEAD verify), Valyu web search, Wikipedia infobox, LLM fallback (only when < 2 verified candidates). Scores candidates by confidence, rejects parking pages and aggregators.",
    inputs: [
      { name: "query", type: "string", required: true, description: "Brand name or ambiguous reference" },
      { name: "limit", type: "number", required: false, description: "Max candidates (default 5, max 10)" },
    ],
    outputs: "ResolveResult { query, candidates: ResolveCandidate[], recommended: number | null, rejected, cost: CostMarker }",
    vendors: ["valyu", "openrouter"],
  },

  // ── Social — Instagram ────────────────────────────────────────────────────

  {
    id: "social.instagram.profile",
    httpMethod: "GET",
    httpPath: "/social/instagram/:handle",
    cliCommand: ["social", "instagram", "profile"],
    summary: "Instagram profile: followers, bio, post count",
    description: "Returns { summary: ProfileSummary, raw } or raw JSON when ?raw=true.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Instagram handle" }],
    outputs: "{ summary: ProfileSummary, raw }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.instagram.posts",
    httpMethod: "GET",
    httpPath: "/social/instagram/:handle/posts",
    cliCommand: ["social", "instagram", "posts"],
    summary: "Recent posts from an Instagram creator",
    description: "Returns a list of recent posts for the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Instagram handle" }],
    outputs: "{ posts: Post[] }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.instagram.reels",
    httpMethod: "GET",
    httpPath: "/social/instagram/:handle/reels",
    cliCommand: ["social", "instagram", "reels"],
    summary: "Recent reels from an Instagram creator",
    description: "Returns reels list for the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Instagram handle" }],
    outputs: "{ reels: Reel[] }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.instagram.highlights",
    httpMethod: "GET",
    httpPath: "/social/instagram/:handle/highlights",
    cliCommand: ["social", "instagram", "highlights"],
    summary: "Instagram story highlights for a creator",
    description: "Returns highlights list for the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Instagram handle" }],
    outputs: "{ highlights }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.instagram.post",
    httpMethod: "POST",
    httpPath: "/social/instagram/post",
    cliCommand: ["social", "instagram", "post"],
    summary: "Single Instagram post info by URL",
    description: "Returns metadata for the given post URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Instagram post URL" }],
    outputs: "Post metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.instagram.comments",
    httpMethod: "POST",
    httpPath: "/social/instagram/post/comments",
    cliCommand: ["social", "instagram", "comments"],
    summary: "Comments on an Instagram post",
    description: "Returns comments for the given post URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Instagram post URL" }],
    outputs: "{ comments }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.instagram.transcript",
    httpMethod: "POST",
    httpPath: "/social/instagram/media/transcript",
    cliCommand: ["social", "instagram", "transcript"],
    summary: "Auto-generated transcript for an Instagram video/reel",
    description: "Returns the transcript for the given media URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Instagram media URL" }],
    outputs: "{ transcript }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.instagram.reelsSearch",
    httpMethod: "GET",
    httpPath: "/social/instagram-reels-search",
    cliCommand: ["social", "instagram", "reels-search"],
    summary: "Search Instagram reels by keyword",
    description: "Returns reels matching the query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ reels }",
    vendors: ["scrapecreators"],
  },

  // ── Social — TikTok ───────────────────────────────────────────────────────

  {
    id: "social.tiktok.profile",
    httpMethod: "GET",
    httpPath: "/social/tiktok/:handle",
    cliCommand: ["social", "tiktok", "profile"],
    summary: "TikTok profile: followers, following, video count",
    description: "Returns { summary: ProfileSummary, raw } or raw JSON when ?raw=true.",
    inputs: [{ name: "handle", type: "string", required: true, description: "TikTok handle" }],
    outputs: "{ summary: ProfileSummary, raw }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.videos",
    httpMethod: "GET",
    httpPath: "/social/tiktok/:handle/videos",
    cliCommand: ["social", "tiktok", "videos"],
    summary: "Recent videos from a TikTok creator",
    description: "Returns a list of recent videos for the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "TikTok handle" }],
    outputs: "{ videos }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.followers",
    httpMethod: "GET",
    httpPath: "/social/tiktok/:handle/followers",
    cliCommand: ["social", "tiktok", "followers"],
    summary: "TikTok follower list for a creator",
    description: "Returns the follower list for the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "TikTok handle" }],
    outputs: "{ followers }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.following",
    httpMethod: "GET",
    httpPath: "/social/tiktok/:handle/following",
    cliCommand: ["social", "tiktok", "following"],
    summary: "Accounts a TikTok creator follows",
    description: "Returns the following list for the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "TikTok handle" }],
    outputs: "{ following }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.live",
    httpMethod: "GET",
    httpPath: "/social/tiktok/:handle/live",
    cliCommand: ["social", "tiktok", "live"],
    summary: "TikTok live stream info for a creator",
    description: "Returns live stream metadata for the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "TikTok handle" }],
    outputs: "{ live }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.video",
    httpMethod: "POST",
    httpPath: "/social/tiktok/video",
    cliCommand: ["social", "tiktok", "video"],
    summary: "TikTok video info / metadata by URL",
    description: "Returns metadata for the given video URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "TikTok video URL" }],
    outputs: "Video metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.comments",
    httpMethod: "POST",
    httpPath: "/social/tiktok/video/comments",
    cliCommand: ["social", "tiktok", "comments"],
    summary: "Comments on a TikTok video",
    description: "Returns comments for the given video URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "TikTok video URL" }],
    outputs: "{ comments }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.transcript",
    httpMethod: "POST",
    httpPath: "/social/tiktok/video/transcript",
    cliCommand: ["social", "tiktok", "transcript"],
    summary: "Auto-generated transcript for a TikTok video",
    description: "Returns the transcript for the given video URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "TikTok video URL" }],
    outputs: "{ transcript }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.search.users",
    httpMethod: "GET",
    httpPath: "/social/tiktok/search/users",
    cliCommand: ["social", "tiktok", "search", "users"],
    summary: "Search TikTok users",
    description: "Returns users matching the query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ users }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.search.hashtag",
    httpMethod: "GET",
    httpPath: "/social/tiktok/search/hashtag",
    cliCommand: ["social", "tiktok", "search", "hashtag"],
    summary: "Search TikTok by hashtag",
    description: "Returns content matching the hashtag query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Hashtag query" }],
    outputs: "{ results }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.search.keyword",
    httpMethod: "GET",
    httpPath: "/social/tiktok/search/keyword",
    cliCommand: ["social", "tiktok", "search", "keyword"],
    summary: "Search TikTok by keyword",
    description: "Returns content matching the keyword query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Keyword query" }],
    outputs: "{ results }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.search.top",
    httpMethod: "GET",
    httpPath: "/social/tiktok/search/top",
    cliCommand: ["social", "tiktok", "search", "top"],
    summary: "Top TikTok search results for a query",
    description: "Returns top results for the query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ results }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.trending.creators",
    httpMethod: "GET",
    httpPath: "/social/tiktok/trending/creators",
    cliCommand: ["social", "tiktok", "trending", "creators"],
    summary: "Trending TikTok creators",
    description: "Returns a list of currently popular TikTok creators.",
    inputs: [],
    outputs: "{ creators }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.trending.hashtags",
    httpMethod: "GET",
    httpPath: "/social/tiktok/trending/hashtags",
    cliCommand: ["social", "tiktok", "trending", "hashtags"],
    summary: "Trending TikTok hashtags",
    description: "Returns a list of currently popular TikTok hashtags.",
    inputs: [],
    outputs: "{ hashtags }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.trending.feed",
    httpMethod: "GET",
    httpPath: "/social/tiktok/trending/feed",
    cliCommand: ["social", "tiktok", "trending", "feed"],
    summary: "TikTok trending feed",
    description: "Returns the current TikTok trending content feed.",
    inputs: [],
    outputs: "{ feed }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.song",
    httpMethod: "GET",
    httpPath: "/social/tiktok/song/:id",
    cliCommand: ["social", "tiktok", "song"],
    summary: "TikTok song details by song ID",
    description: "Returns metadata for the given song ID.",
    inputs: [{ name: "id", type: "string", required: true, description: "TikTok song ID" }],
    outputs: "Song metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktok.songVideos",
    httpMethod: "GET",
    httpPath: "/social/tiktok/song/:id/videos",
    cliCommand: ["social", "tiktok", "song-videos"],
    summary: "Videos using a TikTok song",
    description: "Returns videos that use the given song ID.",
    inputs: [{ name: "id", type: "string", required: true, description: "TikTok song ID" }],
    outputs: "{ videos }",
    vendors: ["scrapecreators"],
  },

  // ── Social — LinkedIn ─────────────────────────────────────────────────────

  {
    id: "social.linkedin.ads",
    httpMethod: "GET",
    httpPath: "/social/linkedin/ads",
    cliCommand: ["social", "linkedin", "ads"],
    summary: "LinkedIn Ad Library search",
    description: "Returns ads matching the query from the LinkedIn Ad Library.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ ads }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.linkedin.profile",
    httpMethod: "GET",
    httpPath: "/social/linkedin/profile/:handle",
    cliCommand: ["social", "linkedin", "profile"],
    summary: "LinkedIn personal profile",
    description: "Returns the profile for the given handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "LinkedIn handle" }],
    outputs: "Profile data",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.linkedin.company",
    httpMethod: "GET",
    httpPath: "/social/linkedin/company/:handle",
    cliCommand: ["social", "linkedin", "company"],
    summary: "LinkedIn company page",
    description: "Returns the company page for the given handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "LinkedIn company handle" }],
    outputs: "Company page data",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.linkedin.companyPosts",
    httpMethod: "GET",
    httpPath: "/social/linkedin/company/:handle/posts",
    cliCommand: ["social", "linkedin", "posts"],
    summary: "Posts published by a LinkedIn company page",
    description: "Returns posts from the given company page.",
    inputs: [{ name: "handle", type: "string", required: true, description: "LinkedIn company handle" }],
    outputs: "{ posts }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.linkedin.post",
    httpMethod: "POST",
    httpPath: "/social/linkedin/post",
    cliCommand: ["social", "linkedin", "post"],
    summary: "Single LinkedIn post by URL",
    description: "Returns metadata for the given post URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "LinkedIn post URL" }],
    outputs: "Post metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — YouTube ──────────────────────────────────────────────────────

  {
    id: "social.youtube.channel",
    httpMethod: "GET",
    httpPath: "/social/youtube/:handle",
    cliCommand: ["social", "youtube", "channel"],
    summary: "YouTube channel info: subscribers, title, video count",
    description: "Returns { summary: ProfileSummary, raw } or raw JSON when ?raw=true.",
    inputs: [{ name: "handle", type: "string", required: true, description: "YouTube @handle" }],
    outputs: "{ summary: ProfileSummary, raw }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.youtube.videos",
    httpMethod: "GET",
    httpPath: "/social/youtube/:handle/videos",
    cliCommand: ["social", "youtube", "videos"],
    summary: "Recent videos from a YouTube channel",
    description: "Returns a list of recent uploads.",
    inputs: [{ name: "handle", type: "string", required: true, description: "YouTube @handle" }],
    outputs: "{ videos }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.youtube.shorts",
    httpMethod: "GET",
    httpPath: "/social/youtube/:handle/shorts",
    cliCommand: ["social", "youtube", "shorts"],
    summary: "Recent YouTube Shorts from a channel",
    description: "Returns Shorts list for the channel.",
    inputs: [{ name: "handle", type: "string", required: true, description: "YouTube @handle" }],
    outputs: "{ shorts }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.youtube.video",
    httpMethod: "POST",
    httpPath: "/social/youtube/video",
    cliCommand: ["social", "youtube", "video"],
    summary: "Single YouTube video info by URL",
    description: "Returns metadata for the given video URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "YouTube video URL" }],
    outputs: "Video metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.youtube.transcript",
    httpMethod: "POST",
    httpPath: "/social/youtube/video/transcript",
    cliCommand: ["social", "youtube", "transcript"],
    summary: "Auto-generated transcript for a YouTube video",
    description: "Returns the transcript for the given video URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "YouTube video URL" }],
    outputs: "{ transcript }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.youtube.comments",
    httpMethod: "POST",
    httpPath: "/social/youtube/video/comments",
    cliCommand: ["social", "youtube", "comments"],
    summary: "Comments on a YouTube video",
    description: "Returns comments for the given video URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "YouTube video URL" }],
    outputs: "{ comments }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.youtube.search",
    httpMethod: "GET",
    httpPath: "/social/youtube/search",
    cliCommand: ["social", "youtube", "search"],
    summary: "Search YouTube videos by keyword",
    description: "Returns videos matching the query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ results }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.youtube.searchHashtag",
    httpMethod: "GET",
    httpPath: "/social/youtube/search/hashtag",
    cliCommand: ["social", "youtube", "search-hashtag"],
    summary: "Search YouTube by hashtag",
    description: "Returns videos matching the hashtag.",
    inputs: [{ name: "q", type: "string", required: true, description: "Hashtag query" }],
    outputs: "{ results }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.youtube.shortsTrending",
    httpMethod: "GET",
    httpPath: "/social/youtube/trending/shorts",
    cliCommand: ["social", "youtube", "trending-shorts"],
    summary: "Trending YouTube Shorts",
    description: "Returns the current trending Shorts feed.",
    inputs: [],
    outputs: "{ shorts }",
    vendors: ["scrapecreators"],
  },

  // ── Social — Twitter / X ──────────────────────────────────────────────────

  {
    id: "social.twitter.profile",
    httpMethod: "GET",
    httpPath: "/social/twitter/:handle",
    cliCommand: ["social", "twitter", "profile"],
    summary: "Twitter/X profile: followers, tweets, bio",
    description: "Returns { summary: ProfileSummary, raw } or raw JSON when ?raw=true.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Twitter handle (no @)" }],
    outputs: "{ summary: ProfileSummary, raw }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.twitter.tweets",
    httpMethod: "GET",
    httpPath: "/social/twitter/:handle/tweets",
    cliCommand: ["social", "twitter", "tweets"],
    summary: "Recent tweets from a Twitter/X user",
    description: "Returns a list of recent tweets.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Twitter handle" }],
    outputs: "{ tweets }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.twitter.tweet",
    httpMethod: "POST",
    httpPath: "/social/twitter/tweet",
    cliCommand: ["social", "twitter", "tweet"],
    summary: "Single tweet info by URL",
    description: "Returns metadata for the given tweet URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Tweet URL" }],
    outputs: "Tweet metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.twitter.tweetTranscript",
    httpMethod: "POST",
    httpPath: "/social/twitter/tweet/transcript",
    cliCommand: ["social", "twitter", "transcript"],
    summary: "Transcript for a Twitter/X video tweet",
    description: "Returns the transcript for the given tweet URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Tweet URL (video)" }],
    outputs: "{ transcript }",
    vendors: ["scrapecreators"],
  },

  // ── Social — Facebook ─────────────────────────────────────────────────────

  {
    id: "social.facebook.profile",
    httpMethod: "GET",
    httpPath: "/social/facebook/:handle",
    cliCommand: ["social", "facebook", "profile"],
    summary: "Facebook page profile",
    description: "Returns { summary: ProfileSummary, raw } or raw JSON when ?raw=true.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Facebook page handle" }],
    outputs: "{ summary: ProfileSummary, raw }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.facebook.posts",
    httpMethod: "GET",
    httpPath: "/social/facebook/:handle/posts",
    cliCommand: ["social", "facebook", "posts"],
    summary: "Posts from a Facebook page",
    description: "Returns a list of recent posts.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Facebook page handle" }],
    outputs: "{ posts }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.facebook.reels",
    httpMethod: "GET",
    httpPath: "/social/facebook/:handle/reels",
    cliCommand: ["social", "facebook", "reels"],
    summary: "Reels from a Facebook page",
    description: "Returns a list of reels.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Facebook page handle" }],
    outputs: "{ reels }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.facebook.photos",
    httpMethod: "GET",
    httpPath: "/social/facebook/:handle/photos",
    cliCommand: ["social", "facebook", "photos"],
    summary: "Photos from a Facebook page",
    description: "Returns a list of photos.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Facebook page handle" }],
    outputs: "{ photos }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.facebook.post",
    httpMethod: "POST",
    httpPath: "/social/facebook/post",
    cliCommand: ["social", "facebook", "post"],
    summary: "Single Facebook post info by URL",
    description: "Returns metadata for the given post URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Facebook post URL" }],
    outputs: "Post metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.facebook.postComments",
    httpMethod: "POST",
    httpPath: "/social/facebook/post/comments",
    cliCommand: ["social", "facebook", "comments"],
    summary: "Comments on a Facebook post",
    description: "Returns comments for the given post URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Facebook post URL" }],
    outputs: "{ comments }",
    vendors: ["scrapecreators"],
  },

  // ── Social — Reddit ───────────────────────────────────────────────────────

  {
    id: "social.reddit.subreddit",
    httpMethod: "GET",
    httpPath: "/social/reddit/:name",
    cliCommand: ["social", "reddit", "subreddit"],
    summary: "Reddit subreddit overview",
    description: "Returns overview data for the given subreddit name.",
    inputs: [{ name: "name", type: "string", required: true, description: "Subreddit name (no r/)" }],
    outputs: "Subreddit data",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.reddit.subredditDetails",
    httpMethod: "GET",
    httpPath: "/social/reddit/:name/details",
    cliCommand: ["social", "reddit", "details"],
    summary: "Reddit subreddit detailed stats",
    description: "Returns detailed stats (subscribers, rules, etc.) for the subreddit.",
    inputs: [{ name: "name", type: "string", required: true, description: "Subreddit name" }],
    outputs: "Subreddit detail data",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.reddit.search",
    httpMethod: "GET",
    httpPath: "/social/reddit-search",
    cliCommand: ["social", "reddit", "search"],
    summary: "Search Reddit posts globally",
    description: "Returns posts matching the query across all of Reddit.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ posts }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.reddit.subredditSearch",
    httpMethod: "GET",
    httpPath: "/social/reddit/:name/search",
    cliCommand: ["social", "reddit", "subreddit-search"],
    summary: "Search posts within a specific subreddit",
    description: "Returns posts matching the query within the given subreddit.",
    inputs: [
      { name: "name", type: "string", required: true, description: "Subreddit name" },
      { name: "q", type: "string", required: true, description: "Search query" },
    ],
    outputs: "{ posts }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.reddit.postComments",
    httpMethod: "POST",
    httpPath: "/social/reddit/post/comments",
    cliCommand: ["social", "reddit", "post-comments"],
    summary: "Comments on a Reddit post",
    description: "Returns comments for the given post URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Reddit post URL" }],
    outputs: "{ comments }",
    vendors: ["scrapecreators"],
  },

  // ── Social — TikTok Shop ──────────────────────────────────────────────────

  {
    id: "social.tiktokShop.search",
    httpMethod: "GET",
    httpPath: "/social/tiktok-shop/search",
    cliCommand: ["social", "tiktok-shop", "search"],
    summary: "Search TikTok Shop products",
    description: "Returns products matching the query in TikTok Shop.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ products }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktokShop.shopProducts",
    httpMethod: "GET",
    httpPath: "/social/tiktok-shop/:shopId/products",
    cliCommand: ["social", "tiktok-shop", "products"],
    summary: "Products from a TikTok Shop by shop ID",
    description: "Returns product list for the given shop ID.",
    inputs: [{ name: "shopId", type: "string", required: true, description: "TikTok Shop ID" }],
    outputs: "{ products }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktokShop.product",
    httpMethod: "POST",
    httpPath: "/social/tiktok-shop/product",
    cliCommand: ["social", "tiktok-shop", "product"],
    summary: "Single TikTok Shop product info by URL",
    description: "Returns product metadata for the given URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "TikTok Shop product URL" }],
    outputs: "Product metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktokShop.productReviews",
    httpMethod: "POST",
    httpPath: "/social/tiktok-shop/product/reviews",
    cliCommand: ["social", "tiktok-shop", "reviews"],
    summary: "Reviews for a TikTok Shop product",
    description: "Returns reviews for the given product URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "TikTok Shop product URL" }],
    outputs: "{ reviews }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.tiktokShop.showcase",
    httpMethod: "GET",
    httpPath: "/social/tiktok-shop/showcase/:handle",
    cliCommand: ["social", "tiktok-shop", "showcase"],
    summary: "TikTok user product showcase",
    description: "Returns the product showcase for the given TikTok handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "TikTok handle" }],
    outputs: "{ showcase }",
    vendors: ["scrapecreators"],
  },

  // ── Social — Threads ──────────────────────────────────────────────────────

  {
    id: "social.threads.profile",
    httpMethod: "GET",
    httpPath: "/social/threads/:handle",
    cliCommand: ["social", "threads", "profile"],
    summary: "Threads (Meta) profile",
    description: "Returns the Threads profile for the given handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Threads handle" }],
    outputs: "Profile data",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.threads.posts",
    httpMethod: "GET",
    httpPath: "/social/threads/:handle/posts",
    cliCommand: ["social", "threads", "posts"],
    summary: "Posts from a Threads account",
    description: "Returns a list of posts from the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Threads handle" }],
    outputs: "{ posts }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.threads.post",
    httpMethod: "POST",
    httpPath: "/social/threads/post",
    cliCommand: ["social", "threads", "post"],
    summary: "Single Threads post by URL",
    description: "Returns metadata for the given post URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Threads post URL" }],
    outputs: "Post metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.threads.search",
    httpMethod: "GET",
    httpPath: "/social/threads-search",
    cliCommand: ["social", "threads", "search"],
    summary: "Search Threads posts",
    description: "Returns posts matching the query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ posts }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.threads.searchUsers",
    httpMethod: "GET",
    httpPath: "/social/threads-search/users",
    cliCommand: ["social", "threads", "search-users"],
    summary: "Search Threads users",
    description: "Returns users matching the query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ users }",
    vendors: ["scrapecreators"],
  },

  // ── Social — Pinterest ────────────────────────────────────────────────────

  {
    id: "social.pinterest.search",
    httpMethod: "GET",
    httpPath: "/social/pinterest/search",
    cliCommand: ["social", "pinterest", "search"],
    summary: "Search Pinterest pins",
    description: "Returns pins matching the query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ pins }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.pinterest.boards",
    httpMethod: "GET",
    httpPath: "/social/pinterest/boards/:handle",
    cliCommand: ["social", "pinterest", "boards"],
    summary: "Pinterest boards for a user",
    description: "Returns boards for the given handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Pinterest handle" }],
    outputs: "{ boards }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.pinterest.pin",
    httpMethod: "POST",
    httpPath: "/social/pinterest/pin",
    cliCommand: ["social", "pinterest", "pin"],
    summary: "Single Pinterest pin by URL",
    description: "Returns metadata for the given pin URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Pinterest pin URL" }],
    outputs: "Pin metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.pinterest.board",
    httpMethod: "POST",
    httpPath: "/social/pinterest/board",
    cliCommand: ["social", "pinterest", "board"],
    summary: "Pinterest board info by URL",
    description: "Returns metadata for the given board URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Pinterest board URL" }],
    outputs: "Board metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — Link aggregators ─────────────────────────────────────────────

  {
    id: "social.links.fetch",
    httpMethod: "GET",
    httpPath: "/social/links/:platform/:handle",
    cliCommand: ["social", "links"],
    summary: "Bio-link aggregator lookup (linktree, komi, pillar, linkbio, linkme)",
    description: "Returns the link aggregator page for the given platform and handle.",
    inputs: [
      {
        name: "platform",
        type: "'linktree'|'komi'|'pillar'|'linkbio'|'linkme'",
        required: true,
        description: "Bio-link platform",
      },
      { name: "handle", type: "string", required: true, description: "Handle on that platform" },
    ],
    outputs: "Link aggregator page data",
    vendors: ["scrapecreators"],
  },

  // ── Social — Bluesky ──────────────────────────────────────────────────────

  {
    id: "social.bluesky.profile",
    httpMethod: "GET",
    httpPath: "/social/bluesky/:handle",
    cliCommand: ["social", "bluesky", "profile"],
    summary: "Bluesky profile",
    description: "Returns the Bluesky profile for the given handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Bluesky handle" }],
    outputs: "Profile data",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.bluesky.posts",
    httpMethod: "GET",
    httpPath: "/social/bluesky/:handle/posts",
    cliCommand: ["social", "bluesky", "posts"],
    summary: "Posts from a Bluesky account",
    description: "Returns a list of posts from the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Bluesky handle" }],
    outputs: "{ posts }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.bluesky.post",
    httpMethod: "POST",
    httpPath: "/social/bluesky/post",
    cliCommand: ["social", "bluesky", "post"],
    summary: "Single Bluesky post by URL",
    description: "Returns metadata for the given post URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Bluesky post URL" }],
    outputs: "Post metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — Twitch ───────────────────────────────────────────────────────

  {
    id: "social.twitch.profile",
    httpMethod: "GET",
    httpPath: "/social/twitch/:handle",
    cliCommand: ["social", "twitch", "profile"],
    summary: "Twitch streamer profile",
    description: "Returns the Twitch profile for the given handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Twitch handle" }],
    outputs: "Profile data",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.twitch.videos",
    httpMethod: "GET",
    httpPath: "/social/twitch/:handle/videos",
    cliCommand: ["social", "twitch", "videos"],
    summary: "VODs from a Twitch streamer",
    description: "Returns a list of VODs for the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Twitch handle" }],
    outputs: "{ videos }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.twitch.schedule",
    httpMethod: "GET",
    httpPath: "/social/twitch/:handle/schedule",
    cliCommand: ["social", "twitch", "schedule"],
    summary: "Twitch stream schedule for a streamer",
    description: "Returns the stream schedule for the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Twitch handle" }],
    outputs: "{ schedule }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.twitch.clip",
    httpMethod: "POST",
    httpPath: "/social/twitch/clip",
    cliCommand: ["social", "twitch", "clip"],
    summary: "Twitch clip info by URL",
    description: "Returns metadata for the given clip URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Twitch clip URL" }],
    outputs: "Clip metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — Facebook Marketplace ─────────────────────────────────────────

  {
    id: "social.facebookMarketplace.search",
    httpMethod: "GET",
    httpPath: "/social/facebook-marketplace/search",
    cliCommand: ["social", "facebook-marketplace", "search"],
    summary: "Search Facebook Marketplace listings",
    description: "Returns listings matching the query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ listings }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.facebookMarketplace.item",
    httpMethod: "POST",
    httpPath: "/social/facebook-marketplace/item",
    cliCommand: ["social", "facebook-marketplace", "item"],
    summary: "Single Facebook Marketplace listing by URL",
    description: "Returns metadata for the given listing URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Facebook Marketplace listing URL" }],
    outputs: "Listing metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — Facebook Events ──────────────────────────────────────────────

  {
    id: "social.facebookEvents.search",
    httpMethod: "GET",
    httpPath: "/social/facebook-events/search",
    cliCommand: ["social", "facebook-events", "search"],
    summary: "Search Facebook events",
    description: "Returns events matching the query.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ events }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.facebookEvents.details",
    httpMethod: "POST",
    httpPath: "/social/facebook-events/details",
    cliCommand: ["social", "facebook-events", "details"],
    summary: "Facebook event details by URL",
    description: "Returns details for the given event URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Facebook event URL" }],
    outputs: "Event metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — Rumble ───────────────────────────────────────────────────────

  {
    id: "social.rumble.search",
    httpMethod: "GET",
    httpPath: "/social/rumble-search",
    cliCommand: ["social", "rumble", "search"],
    summary: "Search Rumble videos",
    description: "Returns videos matching the query on Rumble.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ videos }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.rumble.channelVideos",
    httpMethod: "GET",
    httpPath: "/social/rumble/:handle/videos",
    cliCommand: ["social", "rumble", "videos"],
    summary: "Videos from a Rumble channel",
    description: "Returns a list of videos from the channel.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Rumble channel handle" }],
    outputs: "{ videos }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.rumble.video",
    httpMethod: "POST",
    httpPath: "/social/rumble/video",
    cliCommand: ["social", "rumble", "video"],
    summary: "Single Rumble video info by URL",
    description: "Returns metadata for the given video URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Rumble video URL" }],
    outputs: "Video metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.rumble.videoTranscript",
    httpMethod: "POST",
    httpPath: "/social/rumble/video/transcript",
    cliCommand: ["social", "rumble", "transcript"],
    summary: "Transcript for a Rumble video",
    description: "Returns the transcript for the given video URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Rumble video URL" }],
    outputs: "{ transcript }",
    vendors: ["scrapecreators"],
  },

  // ── Social — SoundCloud ───────────────────────────────────────────────────

  {
    id: "social.soundcloud.artist",
    httpMethod: "POST",
    httpPath: "/social/soundcloud/artist",
    cliCommand: ["social", "soundcloud", "artist"],
    summary: "SoundCloud artist info by URL",
    description: "Returns artist metadata for the given SoundCloud artist URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "SoundCloud artist URL" }],
    outputs: "Artist metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.soundcloud.artistTracks",
    httpMethod: "POST",
    httpPath: "/social/soundcloud/artist/tracks",
    cliCommand: ["social", "soundcloud", "tracks"],
    summary: "Tracks from a SoundCloud artist",
    description: "Returns tracks for the given artist URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "SoundCloud artist URL" }],
    outputs: "{ tracks }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.soundcloud.track",
    httpMethod: "POST",
    httpPath: "/social/soundcloud/track",
    cliCommand: ["social", "soundcloud", "track"],
    summary: "Single SoundCloud track info by URL",
    description: "Returns metadata for the given track URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "SoundCloud track URL" }],
    outputs: "Track metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — Truth Social ─────────────────────────────────────────────────

  {
    id: "social.truthsocial.profile",
    httpMethod: "GET",
    httpPath: "/social/truthsocial/:handle",
    cliCommand: ["social", "truthsocial", "profile"],
    summary: "Truth Social profile",
    description: "Returns the Truth Social profile for the given handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Truth Social handle" }],
    outputs: "Profile data",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.truthsocial.posts",
    httpMethod: "GET",
    httpPath: "/social/truthsocial/:handle/posts",
    cliCommand: ["social", "truthsocial", "posts"],
    summary: "Posts from a Truth Social account",
    description: "Returns a list of posts from the handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Truth Social handle" }],
    outputs: "{ posts }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.truthsocial.post",
    httpMethod: "POST",
    httpPath: "/social/truthsocial/post",
    cliCommand: ["social", "truthsocial", "post"],
    summary: "Single Truth Social post by URL",
    description: "Returns metadata for the given post URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Truth Social post URL" }],
    outputs: "Post metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — Snapchat / Kick ──────────────────────────────────────────────

  {
    id: "social.snapchat.profile",
    httpMethod: "GET",
    httpPath: "/social/snapchat/:handle",
    cliCommand: ["social", "snapchat"],
    summary: "Snapchat profile",
    description: "Returns the Snapchat profile for the given handle.",
    inputs: [{ name: "handle", type: "string", required: true, description: "Snapchat handle" }],
    outputs: "Profile data",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.kick.clip",
    httpMethod: "POST",
    httpPath: "/social/kick/clip",
    cliCommand: ["social", "kick-clip"],
    summary: "Kick clip info by URL",
    description: "Returns metadata for the given Kick clip URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Kick clip URL" }],
    outputs: "Clip metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — Google extras ────────────────────────────────────────────────

  {
    id: "social.google.search",
    httpMethod: "GET",
    httpPath: "/social/google-search",
    cliCommand: ["social", "google", "search"],
    summary: "Google web search",
    description: "Returns search results for the query via Scrapecreators Google endpoint.",
    inputs: [{ name: "q", type: "string", required: true, description: "Search query" }],
    outputs: "{ results }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.google.advertiserAds",
    httpMethod: "GET",
    httpPath: "/social/google-ads/advertiser/:advertiserId",
    cliCommand: ["social", "google", "advertiser-ads"],
    summary: "All ads for a Google advertiser ID",
    description: "Returns all ads visible on the Google Ads Transparency page for the given advertiser ID.",
    inputs: [{ name: "advertiserId", type: "string", required: true, description: "Google advertiser ID (AR…)" }],
    outputs: "{ ads }",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.google.ad",
    httpMethod: "POST",
    httpPath: "/social/google-ads/ad",
    cliCommand: ["social", "google", "ad"],
    summary: "Single Google ad detail by URL",
    description: "Returns metadata for the given Google ad URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Google ad URL" }],
    outputs: "Ad metadata",
    vendors: ["scrapecreators"],
  },

  // ── Social — Spotify ──────────────────────────────────────────────────────

  {
    id: "social.spotify.artist",
    httpMethod: "POST",
    httpPath: "/social/spotify/artist",
    cliCommand: ["social", "spotify", "artist"],
    summary: "Spotify artist info by URL",
    description: "Returns artist metadata for the given Spotify artist URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Spotify artist URL" }],
    outputs: "Artist metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.spotify.track",
    httpMethod: "POST",
    httpPath: "/social/spotify/track",
    cliCommand: ["social", "spotify", "track"],
    summary: "Spotify track info by URL",
    description: "Returns metadata for the given Spotify track URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Spotify track URL" }],
    outputs: "Track metadata",
    vendors: ["scrapecreators"],
  },
  {
    id: "social.spotify.album",
    httpMethod: "POST",
    httpPath: "/social/spotify/album",
    cliCommand: ["social", "spotify", "album"],
    summary: "Spotify album info by URL",
    description: "Returns metadata for the given Spotify album URL.",
    inputs: [{ name: "url", type: "string", required: true, description: "Spotify album URL" }],
    outputs: "Album metadata",
    vendors: ["scrapecreators"],
  },

  // ── Book ─────────────────────────────────────────────────────────────────

  {
    id: "book.build",
    httpMethod: "POST",
    httpPath: "/v1/book",
    cliCommand: ["book"],
    summary: "Build an installable brand-book tar.gz from a domain",
    description:
      "Composite pipeline: resolve domain → brand fetch → ads search → catalog crawl → design palette → optional competitor analysis → compose .org files → bundle workbook .html → tar.gz. Returns application/gzip with SKILL.md + <slug>.workbook.html. Cached per-account by slug for 1 hour; pass force=true to bypass.",
    inputs: [
      { name: "domain", type: "string", required: true, description: "Brand domain (e.g. nike.com)" },
      {
        name: "competitors",
        type: "string[]",
        required: false,
        description: "Competitor domains to include in the book",
      },
      {
        name: "with_video",
        type: "boolean",
        required: false,
        description: "Include video media (stub for wb-0wst.5; passthrough in v1)",
      },
      {
        name: "link_only",
        type: "boolean",
        required: false,
        description: "Embed media as external links instead of downloading bytes",
      },
      {
        name: "force",
        type: "boolean",
        required: false,
        description: "Bypass the 1-hour R2 cache and rebuild from scratch",
      },
    ],
    outputs:
      "application/gzip tar.gz; headers: X-Brandnana-Book-Slug, X-Brandnana-Book-Cost-USD",
    vendors: ["context-dev", "valyu", "scrapecreators"],
  },

  // ── Usage ─────────────────────────────────────────────────────────────────

  {
    id: "usage.get",
    httpMethod: "GET",
    httpPath: "/usage",
    cliCommand: ["usage"],
    summary: "Show vendor call counts, cache hit rate, and estimated cost for your tenant",
    description:
      "Reads from D1 vendor_calls table. Returns per-provider rollups (calls, cache_hits, estimated_cost_usd) and totals for the given time window.",
    inputs: [
      {
        name: "since_hours",
        type: "number",
        required: false,
        description: "Window length in hours (1–2160, default 24)",
      },
    ],
    outputs: "{ tenant, since_hours, api_key, providers: ProviderRollup[], totals }",
  },

  // ── Audit-trace ───────────────────────────────────────────────────────────

  {
    id: "audit.trace",
    httpMethod: "GET",
    httpPath: "",
    cliCommand: ["audit-trace"],
    summary: "Show which brandnana capabilities were exercised in a finished eval run",
    description:
      "Reads .brandnana-trace.jsonl and .brandnana-cost.jsonl from a finished eval workdir. Prints a structured checklist of capabilities used/not-used, plus LIVE cost telemetry. Not a pass/fail gate — pure visibility.",
    inputs: [
      {
        name: "workdir",
        type: "string",
        required: true,
        description: "Path to the eval run directory containing .brandnana-trace.jsonl",
      },
    ],
    outputs: "AuditReport { capabilities, totals, warnings }",
  },

  // ── Health / system ───────────────────────────────────────────────────────

  {
    id: "system.health",
    httpMethod: "GET",
    httpPath: "/health",
    cliCommand: [],
    summary: "API health check: binding + secret status",
    description:
      "Returns status of D1, R2, and Browser bindings plus which secrets are set vs missing. Agent-facing — not a user command.",
    inputs: [],
    outputs: "{ service, status, env, bindings, secrets }",
  },
];

export function getVerb(id: string): Verb | undefined {
  return VERBS.find((v) => v.id === id);
}

export function groupByNamespace(verbs: Verb[] = VERBS): Record<string, Verb[]> {
  const groups: Record<string, Verb[]> = {};
  for (const v of verbs) {
    const ns = v.id.split(".")[0] ?? "_";
    (groups[ns] ??= []).push(v);
  }
  return groups;
}
