// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(unused_unsafe, clippy::all)]
pub fn session_info() -> _rt::String {
    unsafe {
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct RetArea(
            [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
        );
        let mut ret_area = RetArea(
            [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
        );
        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "session-info"]
            fn wit_import1(_: *mut u8);
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import1(_: *mut u8) {
            unreachable!()
        }
        unsafe { wit_import1(ptr0) };
        let l2 = *ptr0.add(0).cast::<*mut u8>();
        let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len4 = l3;
        let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
        let result5 = _rt::string_lift(bytes4);
        result5
    }
}
#[allow(unused_unsafe, clippy::all)]
pub fn vfs_query(sql: &str) -> _rt::String {
    unsafe {
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct RetArea(
            [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
        );
        let mut ret_area = RetArea(
            [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
        );
        let vec0 = sql;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "vfs-query"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
            unreachable!()
        }
        unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
        let l3 = *ptr1.add(0).cast::<*mut u8>();
        let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len5 = l4;
        let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
        let result6 = _rt::string_lift(bytes5);
        result6
    }
}
#[allow(unused_unsafe, clippy::all)]
/// Invoke a registered in-WASM command by name (the universal CLI ABI:
/// argv + stdin → stdout) — a local, pure-compute sandboxed binary (jq/ripgrep),
/// how an agent runs commands without an OS shell. `args` is the command's argv;
/// the host applies each command's arg mode (real wasmtime argv, or fold into the
/// first stdin line for legacy stdin-protocol commands). Gated by `commands`.
pub fn run_command(command: &str, input: &str, args: &[_rt::String]) -> _rt::String {
    unsafe {
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct RetArea(
            [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
        );
        let mut ret_area = RetArea(
            [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
        );
        let vec0 = command;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let vec1 = input;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();
        let vec3 = args;
        let len3 = vec3.len();
        let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
            vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
            ::core::mem::size_of::<*const u8>(),
        );
        let result3 = if layout3.size() != 0 {
            let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
            if ptr.is_null() {
                _rt::alloc::handle_alloc_error(layout3);
            }
            ptr
        } else {
            ::core::ptr::null_mut()
        };
        for (i, e) in vec3.into_iter().enumerate() {
            let base = result3.add(i * (2 * ::core::mem::size_of::<*const u8>()));
            {
                let vec2 = e;
                let ptr2 = vec2.as_ptr().cast::<u8>();
                let len2 = vec2.len();
                *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
            }
        }
        let ptr4 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "run-command"]
            fn wit_import5(
                _: *mut u8,
                _: usize,
                _: *mut u8,
                _: usize,
                _: *mut u8,
                _: usize,
                _: *mut u8,
            );
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import5(
            _: *mut u8,
            _: usize,
            _: *mut u8,
            _: usize,
            _: *mut u8,
            _: usize,
            _: *mut u8,
        ) {
            unreachable!()
        }
        unsafe {
            wit_import5(
                ptr0.cast_mut(),
                len0,
                ptr1.cast_mut(),
                len1,
                result3,
                len3,
                ptr4,
            )
        };
        let l6 = *ptr4.add(0).cast::<*mut u8>();
        let l7 = *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len8 = l7;
        let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
        let result9 = _rt::string_lift(bytes8);
        if layout3.size() != 0 {
            _rt::alloc::dealloc(result3.cast(), layout3);
        }
        result9
    }
}
#[allow(unused_unsafe, clippy::all)]
/// Fetch+extract one URL through the host's Browse capability (Workbooks.Browse).
/// Route B: the host owns the network egress — the component never opens a socket
/// (wasi:http/sockets are NOT granted). Returns the extracted page as a JSON
/// string. Gated by `browse`.
pub fn browse_fetch(url: &str) -> _rt::String {
    unsafe {
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct RetArea(
            [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
        );
        let mut ret_area = RetArea(
            [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
        );
        let vec0 = url;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "browse-fetch"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
            unreachable!()
        }
        unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
        let l3 = *ptr1.add(0).cast::<*mut u8>();
        let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len5 = l4;
        let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
        let result6 = _rt::string_lift(bytes5);
        result6
    }
}
#[allow(unused_unsafe, clippy::all)]
/// Fan a registered command over N inputs CONCURRENTLY across isolated instances
/// (the host/BEAM does the parallelism a single-threaded wasm instance can't —
/// Workbooks.Fabric). `inputs` is a JSON array of stdin strings; returns a JSON
/// array of {"ok": stdout} | {"error": reason}, in order. Gated by `parallel`.
/// (Bound in Instance.Imports.for_caps; declared here so a component can import it.)
pub fn run_command_many(command: &str, inputs: &str) -> _rt::String {
    unsafe {
        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
        struct RetArea(
            [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
        );
        let mut ret_area = RetArea(
            [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
        );
        let vec0 = command;
        let ptr0 = vec0.as_ptr().cast::<u8>();
        let len0 = vec0.len();
        let vec1 = inputs;
        let ptr1 = vec1.as_ptr().cast::<u8>();
        let len1 = vec1.len();
        let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        unsafe extern "C" {
            #[link_name = "run-command-many"]
            fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8);
        }
        #[cfg(not(target_arch = "wasm32"))]
        unsafe extern "C" fn wit_import3(
            _: *mut u8,
            _: usize,
            _: *mut u8,
            _: usize,
            _: *mut u8,
        ) {
            unreachable!()
        }
        unsafe { wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2) };
        let l4 = *ptr2.add(0).cast::<*mut u8>();
        let l5 = *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let len6 = l5;
        let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
        let result7 = _rt::string_lift(bytes6);
        result7
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_run_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::run(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_run<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn run(input: _rt::String) -> _rt::String;
}
#[doc(hidden)]
macro_rules! __export_world_engine_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "run")] unsafe extern "C" fn
        export_run(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_run_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_run")] unsafe extern "C" fn _post_return_run(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_run::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_engine_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::alloc;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_engine_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_engine_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_engine_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:workbooks:engine:engine:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 341] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd8\x01\x01A\x02\x01\
A\x0d\x01@\0\0s\x03\0\x0csession-info\x01\0\x01@\x01\x03sqls\0s\x03\0\x09vfs-que\
ry\x01\x01\x01ps\x01@\x03\x07commands\x05inputs\x04args\x02\0s\x03\0\x0brun-comm\
and\x01\x03\x01@\x01\x03urls\0s\x03\0\x0cbrowse-fetch\x01\x04\x01@\x02\x07comman\
ds\x06inputss\0s\x03\0\x10run-command-many\x01\x05\x01@\x01\x05inputs\0s\x04\0\x03\
run\x01\x06\x04\0\x17workbooks:engine/engine\x04\0\x0b\x0c\x01\0\x06engine\x03\0\
\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bi\
ndgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
