//! The Work kernel — the engine's real front-end + renderer.
//!
//! ONE format: `work-*` web components. The kernel parses the Work front-end
//! (the `.work` shorthand and the HTML element tree share one [`work::Node`]
//! model) and reads its structure:
//!   - parse_headlines : the query surface (structure → rows)
//!   - tangle_plan     : a WIT-world-shaped build plan (work-flow → world)
//!   - validate        : diagnostics over the plan (dangling inputs, no lang)
//!   - check_upgrade   : diff a deployed world vs a new one, gate breaking changes
//!   - render          : Work → `work-*` HTML (work::render_work)
//!
//! Everything is `element + values + nesting + prose`. Org's special fields
//! (TODO state, tags, drawers, source-block header args, SCHEDULED/DEADLINE)
//! are plain attributes on `work-*` elements now — one mechanism, no syntax per
//! concept. See docs/WORK-FORMAT.md. Pure in / pure out, no host calls — the
//! same wasm runs in every surface.
//!
//! The boundary is a WIT-typed Component (the `workbooks:oql` world): every
//! export is string→string, generated by cargo-component. No `unsafe`, no
//! hand-rolled ptr/len ABI — the kernel rides the same Component Model it
//! imposes on user code. The export names + JSON shapes are unchanged: only the
//! front-end syntax behind them moved from org to Work.

use std::collections::{BTreeMap, BTreeSet};

// The Work format: generic Node tree + `.work` shorthand parser + work-* HTML
// renderer (the canonical front-end). See docs/WORK-FORMAT.md.
pub mod work;

// Pure, host-injected time math (no clock, no I/O). The kernel computes *when*
// schedules fire; the host's scheduler fires them. See docs/WORK-FORMAT.md.
pub mod work_time;

use work::Node;

// ── Public kernel API ─────────────────────────────────────────────────────
// Pure string→string functions. The native build (e.g. the `wb` CLI) links
// these as a normal rlib; the wasm Component below wraps the SAME functions.
// One logic, both surfaces — there is no "wasm version" of the kernel logic.

pub fn parse_headlines(src: &str) -> String {
    let arr: Vec<_> = flatten(&work::parse_work(src))
        .iter()
        .map(|(level, n)| {
            serde_json::json!({
                "level": level,
                "title": title_of(n),
                "state": state_of(n),
                "id": n.attrs.get("id"),
                "tags": tags_of(n),
                "props": props_of(n),
                "scheduled": schedule_json(n),
                "deadline": deadline_json(n),
            })
        })
        .collect();
    serde_json::to_string(&arr).unwrap_or_else(|_| "[]".into())
}

pub fn lint(_src: &str) -> String {
    "[]".into()
}

pub fn tangle_plan(src: &str) -> String {
    build_plan(src).to_string()
}

pub fn validate(src: &str) -> String {
    let roots = work::parse_work(src);
    let mut diags = vec![];
    walk_flows(&roots, &mut |flow| {
        let comps = comps_of(flow);
        let produced: BTreeSet<&str> = comps.iter().filter_map(|c| c.out.as_deref()).collect();
        for c in &comps {
            if c.lang.is_none() {
                diags.push(diag("error", &c.name, "component has no source block / language"));
            }
            if let Some(inp) = &c.inp {
                if !produced.contains(inp.as_str()) {
                    diags.push(diag(
                        "error",
                        &c.name,
                        &format!("input `{}` has no upstream producer", inp),
                    ));
                }
            }
        }
    });
    serde_json::to_string(&diags).unwrap_or_else(|_| "[]".into())
}

// Diff a deployed Workbook against a new one and gate breaking changes,
// WIT/Candid-subtyping style: exports may grow, never shrink; imports may
// shrink, never grow; a component's output type may not change. Empty
// diagnostics means the upgrade is safe.
pub fn check_upgrade(old: &str, new: &str) -> String {
    let old = world_sigs(old);
    let new = world_sigs(new);

    let mut diags = vec![];
    for (name, os) in &old {
        let Some(ns) = new.get(name) else {
            diags.push(diag("error", name, "workflow removed (breaking)"));
            continue;
        };
        for e in &os.exports {
            if !ns.exports.contains(e) {
                diags.push(diag("error", name, &format!("export `{}` removed (breaking)", e)));
            }
        }
        for i in &ns.imports {
            if !os.imports.contains(i) {
                diags.push(diag("warn", name, &format!("new capability `{}` now required", i)));
            }
        }
        for (c, oout) in &os.comp_out {
            if let Some(nout) = ns.comp_out.get(c) {
                if oout != nout {
                    diags.push(diag(
                        "error",
                        name,
                        &format!("component `{}` output type changed (breaking)", c),
                    ));
                }
            }
        }
    }
    serde_json::to_string(&diags).unwrap_or_else(|_| "[]".into())
}

pub fn render(src: &str) -> String {
    work::render_work(src)
}

// Pure next-fire helper: given a cron expression and an injected `now` (an
// ISO-8601 instant string), return the first fire time strictly AFTER `now` as
// an ISO-8601 string, or `null` when the cron is invalid / never fires within
// the horizon. The kernel NEVER reads the clock — `now` is always supplied by
// the host, which then performs the actual firing. This is the kernel's whole
// role in scheduling: compute when, never trigger.
pub fn next_fire(cron: &str, now: &str) -> String {
    let result = work_time::Cron::parse(cron)
        .zip(work_time::Instant::parse(now))
        .and_then(|(c, n)| c.next_after(&n))
        .map(|i| i.format());
    match result {
        Some(at) => serde_json::json!({ "at": at }).to_string(),
        None => serde_json::json!({ "at": serde_json::Value::Null }).to_string(),
    }
}

// ── wasm Component boundary (the workbooks:oql world) ──────────────────────
// cargo-component generates `bindings` from wit/world.wit at build time. The
// Component wraps the pure API above; behavior is identical to before the rlib
// split. Compiled only for the wasm target so the native rlib stays clean.
#[cfg(feature = "browser")]
mod browser_abi;

#[cfg(feature = "component")]
#[allow(warnings)]
mod bindings;

#[cfg(feature = "component")]
mod wasm_component {
    use crate::bindings::{self, Guest};

    struct Component;

    impl Guest for Component {
        fn parse_headlines(org: String) -> String {
            crate::parse_headlines(&org)
        }
        fn lint(org: String) -> String {
            crate::lint(&org)
        }
        fn tangle_plan(org: String) -> String {
            crate::tangle_plan(&org)
        }
        fn validate(org: String) -> String {
            crate::validate(&org)
        }
        fn check_upgrade(old: String, new: String) -> String {
            crate::check_upgrade(&old, &new)
        }
        fn render(org: String) -> String {
            crate::render(&org)
        }
    }

    bindings::export!(Component with_types_in bindings);
}

// ── Reading the Work node tree ─────────────────────────────────────────────
// Every former org concept is now a plain attribute on a `work-*` element. The
// readers below derive the SAME values the old org lens produced, so the JSON
// output shapes (parse_headlines / tangle_plan / validate / check_upgrade) are
// byte-for-byte the same contract — only the front-end syntax changed.

// Reserved attribute keys that carry their own meaning and so are NOT surfaced
// as generic "props" (the org `:PROPERTIES:` drawer equivalent).
const RESERVED: &[&str] = &[
    "id", "title", "status", "tag", "assignee", "lang", "in", "out", "deps", "uses", "persist",
    "dir", "due", "scheduled", "at", "start", "end", "cron", "repeat",
];

fn title_of(n: &Node) -> String {
    n.attrs.get("title").cloned().unwrap_or_default()
}

// TODO/DONE state → the `status` attribute (uppercased to match the old org
// keyword surface, e.g. "TODO"/"DONE", `None` when absent).
fn state_of(n: &Node) -> Option<String> {
    n.attrs.get("status").map(|s| s.to_uppercase())
}

// `:tags:` → the `tag` attribute (space-separated) plus `@name` assignee sugar
// surfaced as a tag, matching how org carried both on the headline.
fn tags_of(n: &Node) -> Vec<String> {
    n.attrs
        .get("tag")
        .map(|s| s.split_whitespace().map(String::from).collect())
        .unwrap_or_default()
}

// The `:PROPERTIES:` drawer → every non-reserved attribute, keyed UPPERCASE to
// match the old drawer surface.
fn props_of(n: &Node) -> BTreeMap<String, String> {
    n.attrs
        .iter()
        .filter(|(k, _)| !RESERVED.contains(&k.as_str()))
        .map(|(k, v)| (k.to_uppercase(), v.clone()))
        .collect()
}

// SCHEDULED → a timestamp-shaped object; a `cron` attribute (the SCHEDULE
// drawer equivalent) is reported separately by `schedule_of`.
fn schedule_json(n: &Node) -> serde_json::Value {
    instant_json(n.attrs.get("scheduled").or_else(|| n.attrs.get("at")))
}

// DEADLINE → a timestamp-shaped object.
fn deadline_json(n: &Node) -> serde_json::Value {
    instant_json(n.attrs.get("due").or_else(|| n.attrs.get("deadline")))
}

// An ISO-8601 instant string → the timestamp shape the old parser emitted
// (`{at, repeat, active}`). Pure value math: no clock is read.
fn instant_json(at: Option<&String>) -> serde_json::Value {
    match at {
        Some(at) => serde_json::json!({ "at": at, "repeat": serde_json::Value::Null, "active": true }),
        None => serde_json::Value::Null,
    }
}

// Flatten the node tree to (depth, node) pairs in document order. Depth starts
// at 1 (the old org headline `level`), so the flat shape that `parse_headlines`
// emits and that the flow/component scans rely on is preserved.
fn flatten(roots: &[Node]) -> Vec<(usize, &Node)> {
    fn go<'a>(n: &'a Node, depth: usize, out: &mut Vec<(usize, &'a Node)>) {
        out.push((depth, n));
        for c in &n.children {
            go(c, depth + 1, out);
        }
    }
    let mut out = vec![];
    for r in roots {
        go(r, 1, &mut out);
    }
    out
}

fn is_flow(n: &Node) -> bool {
    n.tag == "work-flow"
}

fn is_component(n: &Node) -> bool {
    n.tag == "work-component"
}

// Visit every `work-flow` node anywhere in the tree (the validate scan).
fn walk_flows(nodes: &[Node], f: &mut impl FnMut(&Node)) {
    for n in nodes {
        if is_flow(n) {
            f(n);
        }
        walk_flows(&n.children, f);
    }
}

// ── header args, now attributes on work-component ──────────────────────────

struct Comp {
    name: String,
    lang: Option<String>,
    deps: Vec<String>,
    uses: Vec<String>,
    inp: Option<String>,
    out: Option<String>,
    persist: bool,
    src: String,
    dir: Option<String>,
}

// A list attribute (deps/uses) splits on commas; absent → empty.
fn list_attr(n: &Node, key: &str) -> Vec<String> {
    match n.attrs.get(key) {
        Some(v) if !v.is_empty() => v.split(',').map(|s| s.trim().to_string()).collect(),
        _ => vec![],
    }
}

fn opt_attr(n: &Node, key: &str) -> Option<String> {
    n.attrs.get(key).filter(|v| !v.is_empty()).cloned()
}

fn comp_of(n: &Node) -> Comp {
    // `lang` present (even empty) means a declared source block, matching how
    // org reported `Some("")` for a fenced block with no language.
    let lang = n.attrs.get("lang").cloned();
    Comp {
        name: title_of(n),
        lang,
        deps: list_attr(n, "deps"),
        uses: list_attr(n, "uses"),
        inp: opt_attr(n, "in"),
        out: opt_attr(n, "out"),
        // a bare `persist` attribute is present-with-empty-value (boolean attr).
        persist: n.attrs.contains_key("persist"),
        src: n.body.clone(),
        dir: opt_attr(n, "dir"),
    }
}

// Every `work-component` descendant of a flow — used by validate + upgrade-gate,
// which reason over the whole component set of a flow (recursing into the tree,
// matching the old flat-scan-by-level behavior).
fn comps_of(flow: &Node) -> Vec<Comp> {
    fn go(nodes: &[Node], out: &mut Vec<Comp>) {
        for n in nodes {
            if is_component(n) {
                out.push(comp_of(n));
            }
            go(&n.children, out);
        }
    }
    let mut out = vec![];
    go(&flow.children, &mut out);
    out
}

struct Sig {
    imports: Vec<String>,
    exports: Vec<String>,
    edges: Vec<(String, String)>,
    comp_out: BTreeMap<String, Option<String>>,
}

fn sig_of(comps: &[Comp]) -> Sig {
    let mut imports: Vec<String> = comps.iter().flat_map(|c| c.uses.clone()).collect();
    imports.sort();
    imports.dedup();

    let mut producer: BTreeMap<String, String> = BTreeMap::new();
    for c in comps {
        if let Some(o) = &c.out {
            producer.insert(o.clone(), c.name.clone());
        }
    }
    let mut edges = vec![];
    let mut consumed: BTreeSet<String> = BTreeSet::new();
    for c in comps {
        if let Some(i) = &c.inp {
            if let Some(f) = producer.get(i) {
                edges.push((f.clone(), c.name.clone()));
                consumed.insert(i.clone());
            }
        }
    }
    let mut exports: Vec<String> = comps
        .iter()
        .filter_map(|c| c.out.clone())
        .filter(|o| !consumed.contains(o))
        .collect();
    exports.sort();
    exports.dedup();

    let comp_out = comps.iter().map(|c| (c.name.clone(), c.out.clone())).collect();
    Sig { imports, exports, edges, comp_out }
}

// SCHEDULE drawer / cron → a `cron` attribute; SCHEDULED → its instant. A cron
// or `repeat` cadence is normalized through the pure time library (cron parsed
// for validity; repeat → RRULE). Next-fire is intentionally NOT computed here:
// the kernel has no `now`, so firing time is a separate pure helper the host
// calls with an injected `now` (see [`next_fire`]). The kernel computes *when*;
// the host's scheduler fires.
fn schedule_of(n: &Node) -> serde_json::Value {
    if let Some(cron) = n.attrs.get("cron") {
        serde_json::json!({ "cron": cron, "valid": work_time::Cron::parse(cron).is_some() })
    } else if let Some(repeat) = n.attrs.get("repeat") {
        match work_time::repeat_to_rrule(repeat) {
            Some(rrule) => serde_json::json!({ "repeat": repeat, "rrule": rrule }),
            None => serde_json::json!({ "repeat": repeat, "rrule": serde_json::Value::Null }),
        }
    } else {
        let sched = schedule_json(n);
        if sched.is_null() {
            serde_json::Value::Null
        } else {
            sched
        }
    }
}

fn comp_json(c: &Comp) -> serde_json::Value {
    serde_json::json!({
        "name": c.name, "lang": c.lang, "deps": c.deps, "uses": c.uses,
        "in": c.inp, "out": c.out, "persist": c.persist, "src": c.src, "dir": c.dir,
    })
}

// ── job 2: the build plan (Work flow → WIT world) ──────────────────────────

/// Recursively build a world. A `work-flow` has children; a `work-component`
/// child (with a source block) is a leaf, a nested `work-flow` child is a
/// sub-world. Direct `work-component` children are this world's components;
/// nested `work-flow` children are sub-worlds. The whole tree compiles into one
/// nested DAG.
fn build_world(flow: &Node) -> serde_json::Value {
    let mut comps: Vec<Comp> = vec![];
    let mut subworlds = vec![];
    for child in &flow.children {
        if is_flow(child) {
            subworlds.push(build_world(child));
        } else if is_component(child) {
            comps.push(comp_of(child));
        }
    }
    let sig = sig_of(&comps);
    let components: Vec<_> = comps.iter().map(comp_json).collect();
    let edges: Vec<_> = sig
        .edges
        .iter()
        .map(|(f, t)| serde_json::json!({ "from": f, "to": t }))
        .collect();
    serde_json::json!({
        "name": title_of(flow),
        "schedule": schedule_of(flow),
        "imports": sig.imports,
        "exports": sig.exports,
        "components": components,
        "edges": edges,
        "workflows": subworlds,
    })
}

fn build_plan(src: &str) -> serde_json::Value {
    let roots = work::parse_work(src);
    let worlds: Vec<_> = top_flows(&roots).iter().map(|f| build_world(f)).collect();
    serde_json::json!({ "worlds": worlds })
}

// The top-most `work-flow` in each branch — recursion stops descending once a
// flow is found (its sub-flows are handled by `build_world`), so a flow nested
// under another flow is not also a top-level world.
fn top_flows(nodes: &[Node]) -> Vec<&Node> {
    let mut out = vec![];
    for n in nodes {
        if is_flow(n) {
            out.push(n);
        } else {
            out.extend(top_flows(&n.children));
        }
    }
    out
}

// ── job 4: upgrade-compatibility gate (Motoko-style) ──────────────────────

fn world_sigs(src: &str) -> BTreeMap<String, Sig> {
    let roots = work::parse_work(src);
    let mut m = BTreeMap::new();
    for flow in top_flows(&roots) {
        m.insert(title_of(flow), sig_of(&comps_of(flow)));
    }
    m
}

fn diag(level: &str, scope: &str, msg: &str) -> serde_json::Value {
    serde_json::json!({ "level": level, "scope": scope, "message": msg })
}

#[cfg(test)]
mod tests {
    use super::*;

    const FLOW: &str = r#"
work-flow "etl"
  work-component "extract" lang=rust out=raw
  work-component "transform" lang=rust in=raw out=clean uses=fetch
  work-component "load" lang=rust in=clean
"#;

    #[test]
    fn parse_headlines_shape() {
        let json: serde_json::Value =
            serde_json::from_str(&parse_headlines(FLOW)).unwrap();
        let rows = json.as_array().unwrap();
        assert_eq!(rows.len(), 4);
        assert_eq!(rows[0]["level"], 1);
        assert_eq!(rows[0]["title"], "etl");
        assert_eq!(rows[1]["level"], 2);
        assert_eq!(rows[1]["title"], "extract");
    }

    #[test]
    fn parse_headlines_status_tags_props() {
        let src = "work-task \"Ship\" status=todo tag=\"urgent backend\" owner=kai\n";
        let json: serde_json::Value =
            serde_json::from_str(&parse_headlines(src)).unwrap();
        let row = &json.as_array().unwrap()[0];
        assert_eq!(row["state"], "TODO");
        assert_eq!(row["tags"], serde_json::json!(["urgent", "backend"]));
        assert_eq!(row["props"]["OWNER"], "kai");
    }

    #[test]
    fn tangle_plan_world() {
        let plan: serde_json::Value =
            serde_json::from_str(&tangle_plan(FLOW)).unwrap();
        let worlds = plan["worlds"].as_array().unwrap();
        assert_eq!(worlds.len(), 1);
        let w = &worlds[0];
        assert_eq!(w["name"], "etl");
        assert_eq!(w["components"].as_array().unwrap().len(), 3);
        // raw + clean are both consumed → only nothing-but-`clean`? load has no
        // out, raw consumed by transform, clean consumed by load → no exports.
        assert_eq!(w["exports"].as_array().unwrap().len(), 0);
        assert_eq!(w["imports"], serde_json::json!(["fetch"]));
        assert_eq!(w["edges"].as_array().unwrap().len(), 2);
    }

    #[test]
    fn tangle_plan_cron_schedule() {
        let src = "work-flow \"nightly\" cron=\"0 9 * * 1\"\n  work-component \"job\" lang=rust\n";
        let plan: serde_json::Value = serde_json::from_str(&tangle_plan(src)).unwrap();
        assert_eq!(plan["worlds"][0]["schedule"]["cron"], "0 9 * * 1");
    }

    #[test]
    fn validate_flags_missing_lang_and_dangling_input() {
        let src = "work-flow \"f\"\n  work-component \"a\"\n  work-component \"b\" lang=rust in=ghost\n";
        let diags: serde_json::Value = serde_json::from_str(&validate(src)).unwrap();
        let arr = diags.as_array().unwrap();
        assert!(arr.iter().any(|d| d["scope"] == "a" && d["message"]
            .as_str()
            .unwrap()
            .contains("no source block")));
        assert!(arr.iter().any(|d| d["scope"] == "b" && d["message"]
            .as_str()
            .unwrap()
            .contains("no upstream producer")));
    }

    #[test]
    fn validate_clean_flow() {
        assert_eq!(validate(FLOW), "[]");
    }

    #[test]
    fn check_upgrade_export_removed_is_breaking() {
        let old = "work-flow \"f\"\n  work-component \"a\" lang=rust out=v1\n";
        let new = "work-flow \"f\"\n  work-component \"a\" lang=rust\n";
        let diags: serde_json::Value = serde_json::from_str(&check_upgrade(old, new)).unwrap();
        let arr = diags.as_array().unwrap();
        assert!(arr.iter().any(|d| d["level"] == "error"
            && d["message"].as_str().unwrap().contains("export `v1` removed")));
    }

    #[test]
    fn check_upgrade_identical_is_safe() {
        assert_eq!(check_upgrade(FLOW, FLOW), "[]");
    }

    #[test]
    fn render_emits_work_html() {
        let html = render("work-flow \"etl\"\n  work-component \"x\" lang=rust\n");
        assert!(html.contains("<work-flow"));
        assert!(html.contains("<work-component"));
        assert!(html.contains("title=\"etl\""));
    }
}
