//! OQL — the opinionated Org kernel, on orgize (MIT).
//!
//! ONE Org engine: orgize parses + renders; our exports are the opinionated lens.
//!   - parse_headlines : the query surface (structure → rows)
//!   - tangle_plan     : a WIT-world-shaped build plan (workflow → world)
//!   - validate        : diagnostics over the plan (dangling inputs, no lang)
//!   - check_upgrade   : diff a deployed world vs a new one, gate breaking changes
//!   - render          : Org → rich HTML (orgize to_html)
//!
//! Org is a language, not just syntax: TODO state, tags, drawers, source blocks
//! + header args (:deps/:uses/:in/:out/:persist/:dir), and timestamps
//! (SCHEDULED/DEADLINE) all carry meaning. Pure in / pure out, no host calls —
//! the same wasm runs in every surface.
//!
//! The boundary is a WIT-typed Component (the `workbooks:oql` world): every
//! export is string→string, generated by cargo-component. No `unsafe`, no
//! hand-rolled ptr/len ABI — the kernel rides the same Component Model it
//! imposes on user code.

use orgize::ast::SourceBlock;
use orgize::rowan::ast::AstNode;
use orgize::{Org, SyntaxKind, SyntaxNode};
use std::collections::{BTreeMap, BTreeSet};

// cargo-component generates `bindings` from wit/world.wit at build time.
#[allow(warnings)]
mod bindings;
use bindings::Guest;

struct Component;

impl Guest for Component {
    fn parse_headlines(org: String) -> String {
        let arr: Vec<_> = parse(&org)
            .iter()
            .map(|h| {
                serde_json::json!({
                    "level": h.level,
                    "title": h.title,
                    "state": h.state,
                    "id": h.props.get("ID"),
                    "tags": h.tags,
                    "props": h.props,
                    "scheduled": h.scheduled.as_ref().map(|t| t.json()),
                    "deadline": h.deadline.as_ref().map(|t| t.json()),
                })
            })
            .collect();
        serde_json::to_string(&arr).unwrap_or_else(|_| "[]".into())
    }

    fn lint(_org: String) -> String {
        "[]".into()
    }

    fn tangle_plan(org: String) -> String {
        build_plan(&org).to_string()
    }

    fn validate(org: String) -> String {
        let hs = parse(&org);
        let mut diags = vec![];
        for (i, h) in hs.iter().enumerate() {
            if !h.has_tag("workflow") {
                continue;
            }
            let comps = comps_of(h, &hs, i);
            let produced: BTreeSet<&str> = comps.iter().filter_map(|c| c.out.as_deref()).collect();
            for c in &comps {
                if c.lang.is_none() {
                    diags.push(diag("error", &c.name, "component has no source block / language"));
                }
                if let Some(inp) = &c.inp {
                    if !produced.contains(inp.as_str()) {
                        diags.push(diag(
                            "error",
                            &c.name,
                            &format!("input `{}` has no upstream producer", inp),
                        ));
                    }
                }
            }
        }
        serde_json::to_string(&diags).unwrap_or_else(|_| "[]".into())
    }

    // Diff a deployed Workbook against a new one and gate breaking changes,
    // WIT/Candid-subtyping style: exports may grow, never shrink; imports may
    // shrink, never grow; a component's output type may not change. Empty
    // diagnostics means the upgrade is safe.
    fn check_upgrade(old: String, new: String) -> String {
        let old = world_sigs(&old);
        let new = world_sigs(&new);

        let mut diags = vec![];
        for (name, os) in &old {
            let Some(ns) = new.get(name) else {
                diags.push(diag("error", name, "workflow removed (breaking)"));
                continue;
            };
            for e in &os.exports {
                if !ns.exports.contains(e) {
                    diags.push(diag("error", name, &format!("export `{}` removed (breaking)", e)));
                }
            }
            for i in &ns.imports {
                if !os.imports.contains(i) {
                    diags.push(diag("warn", name, &format!("new capability `{}` now required", i)));
                }
            }
            for (c, oout) in &os.comp_out {
                if let Some(nout) = ns.comp_out.get(c) {
                    if oout != nout {
                        diags.push(diag(
                            "error",
                            name,
                            &format!("component `{}` output type changed (breaking)", c),
                        ));
                    }
                }
            }
        }
        serde_json::to_string(&diags).unwrap_or_else(|_| "[]".into())
    }

    fn render(org: String) -> String {
        Org::parse(&org).to_html()
    }
}

bindings::export!(Component with_types_in bindings);

// --- Org timestamps (scheduling) -----------------------------------------

#[derive(Clone)]
struct Timestamp {
    date: String,
    time: Option<String>,
    repeat: Option<String>,
    active: bool,
}

impl Timestamp {
    fn iso(&self) -> String {
        match &self.time {
            Some(t) => format!("{}T{}", self.date, t),
            None => self.date.clone(),
        }
    }
    fn json(&self) -> serde_json::Value {
        serde_json::json!({ "at": self.iso(), "repeat": self.repeat, "active": self.active })
    }
}

fn parse_timestamp(s: &str) -> Option<Timestamp> {
    let s = s.trim();
    let (active, inner) = match s.chars().next()? {
        '<' if s.ends_with('>') => (true, &s[1..s.len() - 1]),
        '[' if s.ends_with(']') => (false, &s[1..s.len() - 1]),
        _ => return None,
    };
    let (mut date, mut time, mut repeat) = (None, None, None);
    for tok in inner.split_whitespace() {
        if date.is_none() && tok.len() == 10 && tok.as_bytes()[4] == b'-' {
            date = Some(tok.to_string());
        } else if tok.contains(':') {
            time = Some(tok.to_string());
        } else if tok.starts_with('+') || tok.starts_with(".+") || tok.starts_with("++") {
            repeat = Some(tok.to_string());
        }
    }
    date.map(|date| Timestamp { date, time, repeat, active })
}

// --- the Org lens ---------------------------------------------------------

struct Src {
    lang: String,
    args: String,
    body: String,
}

struct Headline {
    level: usize,
    title: String,
    state: Option<String>,
    tags: Vec<String>,
    props: BTreeMap<String, String>,
    scheduled: Option<Timestamp>,
    deadline: Option<Timestamp>,
    src: Option<Src>,
}

impl Headline {
    fn has_tag(&self, t: &str) -> bool {
        self.tags.iter().any(|x| x == t)
    }
}

// Parse with orgize, fill our Headline structs — all downstream logic (tangle,
// validate, render) is unchanged; only the parser swapped to the real library.
fn parse(src: &str) -> Vec<Headline> {
    let org = Org::parse(src);
    let root = SyntaxNode::new_root(org.green().clone());
    let mut out = Vec::new();
    walk(&root, &mut out);
    out
}

fn walk(node: &SyntaxNode, out: &mut Vec<Headline>) {
    for child in node.children() {
        if child.kind() == SyntaxKind::HEADLINE {
            if let Some(hl) = orgize::ast::Headline::cast(child.clone()) {
                out.push(headline_of(&hl));
            }
            walk(&child, out);
        }
    }
}

fn headline_of(hl: &orgize::ast::Headline) -> Headline {
    let tags: Vec<String> = hl.tags().map(|t| t.to_string()).collect();
    let state = hl.todo_keyword().map(|t| t.to_string());

    let mut props = BTreeMap::new();
    if let Some(p) = hl.properties() {
        for (k, v) in p.iter() {
            props.insert(k.to_string().to_uppercase(), v.to_string().trim().to_string());
        }
    }

    let (scheduled, deadline) = match hl.planning() {
        Some(p) => (
            p.scheduled().and_then(|t| parse_timestamp(&t.raw())),
            p.deadline().and_then(|t| parse_timestamp(&t.raw())),
        ),
        None => (None, None),
    };

    Headline {
        level: hl.level(),
        title: strip_tags(hl.title_raw().trim()),
        state,
        tags,
        props,
        scheduled,
        deadline,
        src: source_of(hl),
    }
}

fn strip_tags(title: &str) -> String {
    if let Some(idx) = title.rfind(char::is_whitespace) {
        let tail = &title[idx + 1..];
        if tail.len() >= 2 && tail.starts_with(':') && tail.ends_with(':') {
            return title[..idx].trim_end().to_string();
        }
    }
    title.to_string()
}

fn source_of(hl: &orgize::ast::Headline) -> Option<Src> {
    let section = hl.section()?;
    section
        .syntax()
        .children()
        .find(|n| n.kind() == SyntaxKind::SOURCE_BLOCK)
        .and_then(SourceBlock::cast)
        .map(|b| Src {
            lang: b.language().map(|t| t.to_string()).unwrap_or_default(),
            args: b.parameters().map(|p| p.to_string().trim().to_string()).unwrap_or_default(),
            body: b.value(),
        })
}

// --- header args ----------------------------------------------------------

#[derive(Default)]
struct Args {
    deps: Vec<String>,
    uses: Vec<String>,
    inp: Option<String>,
    out: Option<String>,
    persist: bool,
    dir: Option<String>,
}

fn parse_args(args: &str) -> Args {
    let mut a = Args::default();
    let toks: Vec<&str> = args.split_whitespace().collect();
    let mut i = 0;
    while i < toks.len() {
        let val = toks.get(i + 1).copied();
        match toks[i] {
            ":deps" => {
                if let Some(v) = val {
                    a.deps = v.split(',').map(String::from).collect();
                    i += 1;
                }
            }
            ":uses" => {
                if let Some(v) = val {
                    a.uses.push(v.to_string());
                    i += 1;
                }
            }
            ":in" => {
                if let Some(v) = val {
                    a.inp = Some(v.to_string());
                    i += 1;
                }
            }
            ":out" => {
                if let Some(v) = val {
                    a.out = Some(v.to_string());
                    i += 1;
                }
            }
            // Motoko-style orthogonal persistence: this component's state
            // survives redeploys; the runtime keeps its memory.
            ":persist" => a.persist = true,
            // Reference a real project directory (its own Cargo.toml/package.json)
            // instead of an inline source block.
            ":dir" => {
                if let Some(v) = val {
                    a.dir = Some(v.to_string());
                    i += 1;
                }
            }
            _ => {}
        }
        i += 1;
    }
    a
}

// --- job 2: the build plan (Org workflow → WIT world) --------------------

struct Comp {
    name: String,
    lang: Option<String>,
    deps: Vec<String>,
    uses: Vec<String>,
    inp: Option<String>,
    out: Option<String>,
    persist: bool,
    src: String,
    dir: Option<String>,
}

fn comp_of(h: &Headline) -> Comp {
    let a = h.src.as_ref().map(|s| parse_args(&s.args)).unwrap_or_default();
    Comp {
        name: h.title.clone(),
        lang: h.src.as_ref().map(|s| s.lang.clone()),
        deps: a.deps,
        uses: a.uses,
        inp: a.inp,
        out: a.out,
        persist: a.persist,
        src: h.src.as_ref().map(|s| s.body.clone()).unwrap_or_default(),
        dir: a.dir,
    }
}

// Flat collection of every `:component:` descendant — used by validate +
// upgrade-gate, which reason over the whole component set of a workflow.
fn comps_of(h: &Headline, all: &[Headline], idx: usize) -> Vec<Comp> {
    let mut comps = vec![];
    let mut j = idx + 1;
    while j < all.len() && all[j].level > h.level {
        if all[j].has_tag("component") {
            comps.push(comp_of(&all[j]));
        }
        j += 1;
    }
    comps
}

struct Sig {
    imports: Vec<String>,
    exports: Vec<String>,
    edges: Vec<(String, String)>,
    comp_out: BTreeMap<String, Option<String>>,
}

fn sig_of(comps: &[Comp]) -> Sig {
    let mut imports: Vec<String> = comps.iter().flat_map(|c| c.uses.clone()).collect();
    imports.sort();
    imports.dedup();

    let mut producer: BTreeMap<String, String> = BTreeMap::new();
    for c in comps {
        if let Some(o) = &c.out {
            producer.insert(o.clone(), c.name.clone());
        }
    }
    let mut edges = vec![];
    let mut consumed: BTreeSet<String> = BTreeSet::new();
    for c in comps {
        if let Some(i) = &c.inp {
            if let Some(f) = producer.get(i) {
                edges.push((f.clone(), c.name.clone()));
                consumed.insert(i.clone());
            }
        }
    }
    let mut exports: Vec<String> = comps
        .iter()
        .filter_map(|c| c.out.clone())
        .filter(|o| !consumed.contains(o))
        .collect();
    exports.sort();
    exports.dedup();

    let comp_out = comps.iter().map(|c| (c.name.clone(), c.out.clone())).collect();
    Sig { imports, exports, edges, comp_out }
}

fn schedule_of(h: &Headline) -> serde_json::Value {
    if let Some(cron) = h.props.get("SCHEDULE") {
        serde_json::json!({ "cron": cron })
    } else if let Some(ts) = &h.scheduled {
        ts.json()
    } else {
        serde_json::Value::Null
    }
}

fn comp_json(c: &Comp) -> serde_json::Value {
    serde_json::json!({
        "name": c.name, "lang": c.lang, "deps": c.deps, "uses": c.uses,
        "in": c.inp, "out": c.out, "persist": c.persist, "src": c.src, "dir": c.dir,
    })
}

fn subtree_end(all: &[Headline], i: usize) -> usize {
    let level = all[i].level;
    let mut j = i + 1;
    while j < all.len() && all[j].level > level {
        j += 1;
    }
    j
}

/// Recursively build a world. A Workflow has Tasks; a Task is either a leaf
/// (`:component:` with a source block) or a sub-Workflow (recursion). Direct
/// `:component:` children are this world's components; nested `:workflow:`
/// children are sub-worlds. The whole tree compiles into one nested DAG.
fn build_world(all: &[Headline], i: usize) -> serde_json::Value {
    let h = &all[i];
    let mut comps: Vec<Comp> = vec![];
    let mut subworlds = vec![];
    let mut j = i + 1;
    while j < all.len() && all[j].level > h.level {
        if all[j].has_tag("workflow") {
            subworlds.push(build_world(all, j));
            j = subtree_end(all, j);
        } else if all[j].has_tag("component") {
            comps.push(comp_of(&all[j]));
            j += 1;
        } else {
            j += 1;
        }
    }
    let sig = sig_of(&comps);
    let components: Vec<_> = comps.iter().map(comp_json).collect();
    let edges: Vec<_> = sig
        .edges
        .iter()
        .map(|(f, t)| serde_json::json!({ "from": f, "to": t }))
        .collect();
    serde_json::json!({
        "name": h.title,
        "schedule": schedule_of(h),
        "imports": sig.imports,
        "exports": sig.exports,
        "components": components,
        "edges": edges,
        "workflows": subworlds,
    })
}

fn build_plan(src: &str) -> serde_json::Value {
    let hs = parse(src);
    let mut worlds = vec![];
    let mut i = 0;
    while i < hs.len() {
        if hs[i].has_tag("workflow") {
            worlds.push(build_world(&hs, i));
            i = subtree_end(&hs, i);
        } else {
            i += 1;
        }
    }
    serde_json::json!({ "worlds": worlds })
}

// --- job 3 helpers: build plan (Org workflow → WIT world) ----------------
// (parse/build_world/build_plan above; the exports live in `impl Guest`)

// --- job 4: upgrade-compatibility gate (Motoko-style) --------------------

fn world_sigs(src: &str) -> BTreeMap<String, Sig> {
    let hs = parse(src);
    let mut m = BTreeMap::new();
    for (i, h) in hs.iter().enumerate() {
        if h.has_tag("workflow") {
            m.insert(h.title.clone(), sig_of(&comps_of(h, &hs, i)));
        }
    }
    m
}

fn diag(level: &str, scope: &str, msg: &str) -> serde_json::Value {
    serde_json::json!({ "level": level, "scope": scope, "message": msg })
}
