defmodule CliNameTest do
  @moduledoc """
  GUARDRAIL: the CLI is named `work`. This test fails if ANY stale CLI name (`wb`
  or `wbx`, as a command invocation) survives anywhere in the tree — so a rename
  can never again be "mostly done". It is the enforcement mechanism, not a vibe:
  green here == the rename is complete; red lists every offender with file:line.

  It targets COMMAND INVOCATIONS only — `wb <verb>`, `wbx <verb>`, inline `` `wb ` ``,
  the old escript name, the agent tool name, usage strings. It deliberately does NOT
  match bead IDs (`wb-0lw8`), module/var names, or `workbooks`/`work-*`/`webhook`
  substrings (word-boundaried, hyphen excluded).
  """
  use ExUnit.Case, async: true

  @repo Path.expand("../..", __DIR__)

  # Scan the WHOLE repo — NOT a dir allow-list. A missed directory (desktop/scripts,
  # .github, runtime/scripts) is exactly how a rename ends up "mostly done".
  @exts ~w(.ex .exs .org .md .svelte .ts .js .mjs .cjs .json .toml .sh .txt .html .yml .yaml)
  @skip_names [Path.basename(__ENV__.file)]

  # `wb`/`wbx` followed by ANY command word — NOT a verb allow-list (a missed verb
  # is exactly how a rename ends up "mostly done"). The space requirement keeps bead
  # IDs (`wb-0lw8` — hyphen, no space) and `workbooks`/`webhook` safe. The lookbehind
  # rejects mid-word matches (`newb deploy`).
  @cmd_re ~r/(?<![\w-])wbx?\s+[A-Za-z]/
  # `wb #{interp}` — an interpolated command (`"wb #{task} …"`), which the plain
  # `[A-Za-z]` form missed and shipped a stale `wb`. Requires `#{` (not `wb # comment`).
  @interp_re ~r/(?<![\w-])wbx?\s+#\{/
  # Inline code-fenced bare command: `wb` / `wbx` / `wb ` at a backtick.
  @backtick_re ~r/`wbx?(?:`|\s)/
  @escript_re ~r/\bwb-rt\b/
  @tool_re ~r/name:\s*"wbx?"/
  @usage_re ~r/\busage:\s*wbx?\b/
  # Bare standalone `wbx` anywhere (the in-flight rename's prose). `wbx` is not a bead
  # prefix, so this is safe; bare `wb` is NOT checked (it would hit `wb-…` bead IDs).
  @bare_wbx_re ~r/\bwbx\b/
  # The `CLI_BIN: wb` toolkit sentinel — a bare `wb` the @cmd_re/@bare_wbx_re can't catch
  # (no following verb, not `wbx`). It means "this toolkit's binary IS the built-in CLI",
  # which is now `work`. A stale one ships the agent a dead command suggestion (the bug
  # this gate now prevents — toolkit_injection direct-verb).
  @cli_bin_re ~r/CLI_BIN:\s*wbx?\b/i
  # The HTML `cli="wb"` attribute on a <work-toolkit>/manifest — the work-* analogue
  # of CLI_BIN. Same meaning ("this kit's binary IS the built-in CLI" = now `work`),
  # but an attribute the org-form @cli_bin_re can't see. A stale one shipped agents a
  # dead `wb …` suggestion (the toolkit-injection direct-verb bug).
  @cli_attr_re ~r/\bcli="wbx?"/

  @patterns [@cmd_re, @interp_re, @backtick_re, @escript_re, @tool_re, @usage_re, @bare_wbx_re, @cli_bin_re, @cli_attr_re]

  # Whole-repo line-by-line scan over every tracked source file — inherently slow,
  # well past the 60s ExUnit default.
  @tag timeout: 600_000
  test "no stale `wb`/`wbx` CLI references survive (the CLI is `work`)" do
    offenders =
      tracked_files()
      |> Enum.filter(&(Path.extname(&1) in @exts))
      |> Enum.reject(&(Path.basename(&1) in @skip_names))
      |> Enum.map(&Path.join(@repo, &1))
      |> Enum.filter(&File.regular?/1)
      |> Enum.flat_map(&scan_file/1)

    if offenders != [] do
      sample = offenders |> Enum.take(60) |> Enum.map_join("\n", & &1)
      flunk(
        "#{length(offenders)} stale CLI-name reference(s) — the CLI is `work`, not `wb`/`wbx`. " <>
          "Fix every one (this gate is how we keep the rename complete):\n" <> sample
      )
    end
  end

  # SOURCE = git-tracked files only. Untracked local artifacts (gitignored build
  # output like generated audio scripts, scratch files) are NOT a source CLI surface
  # and must not gate the rename — they aren't shipped and aren't reviewed. This also
  # keeps the scan bounded to what's actually in the repo, not whatever happens to be
  # in a contributor's working tree.
  defp tracked_files do
    {out, 0} = System.cmd("git", ["ls-files", "-z"], cd: @repo)
    out |> String.split("\0", trim: true)
  end

  defp scan_file(path) do
    rel = Path.relative_to(path, @repo)
    lines = File.stream!(path) |> Enum.to_list()

    # Skip GENERATED artifacts (e.g. examples/groundwork/BOARD.org, regenerated by
    # Workbooks.Groundskeeper.Board from bd issue TITLES). They echo historical text
    # like "rename CLI: wb → wbx" — that's a record of past work, not a source CLI
    # reference, so it must not gate the rename. This guardrail validates SOURCE; every
    # real CLI surface (code/skills/docs) is still scanned.
    generated? = lines |> Enum.take(3) |> Enum.any?(&String.contains?(&1, "#+GENERATED:"))

    if generated? do
      []
    else
      lines
      |> Enum.with_index(1)
      # Skip minified/bundled blobs (generated pack.bundle.json, dist specimens):
      # a real `wb <verb>` CLI reference lives on a normal source line, never a
      # multi-megabyte minified one — and the lookbehind patterns backtrack
      # catastrophically on them (Regex.safe_run timeout). 8 KB is far above any
      # hand-written source line.
      |> Enum.reject(fn {line, _} -> byte_size(line) > 8_192 end)
      |> Enum.flat_map(fn {line, n} ->
        if Enum.any?(@patterns, &Regex.match?(&1, line)),
          do: ["  #{rel}:#{n}: #{String.trim(line) |> String.slice(0, 100)}"],
          else: []
      end)
    end
  end
end
