#!/usr/bin/env node
// build · produce a real, buildless-friendly dist/ from the src tree.
//
// One import gives a consumer (and the agent-eval render_fidelity harness) the
// whole set — REAL components, never stubs:
//
//   dist/workponents.js   bundled-but-UNMINIFIED ESM. Registers all 45 <work-*>
//                         elements from one import + re-exports the classes.
//                         Lit (and its directives) are BUNDLED in — the file is
//                         fully self-contained, no import map / peer install
//                         needed (buildless drop-in: `<script type=module
//                         src=…/dist/workponents.js>` or `import` it). The lazy
//                         CDN engine tiers (Observable Plot / MapLibre / CodeMirror
//                         / MiniSearch / model-viewer / mammoth / docx / pptxgen /
//                         Manifold) stay LAZY `import()` of their CDN specifiers —
//                         NOT bundled — so the floor never pulls a heavy engine and
//                         the powered tier still resolves on demand. esbuild leaves
//                         them external automatically: every engine import() takes a
//                         runtime VARIABLE specifier (the *_CDN consts), which a
//                         bundler cannot and must not inline.
//   dist/theme.css        the design tokens (src/theme/tokens.css) — the theme
//                         contract every element reads via --work-*.
//
// Build dep: esbuild, resolved from the shared desktop node_modules (the worktree
// symlinks ./node_modules → desktop/node_modules; the gate already depends on that
// tree for playwright/sharp). No new install, no extra runtime dep. If esbuild is
// absent the build fails loud with the one command to provision it.

import { build } from "esbuild";
import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "src");
const DIST = join(ROOT, "dist");

const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));

async function main() {
  mkdirSync(DIST, { recursive: true });

  const banner =
    `/* @work.books/workponents ${pkg.version} — bundled ESM (Lit inlined; lazy CDN engine tiers external).\n` +
    `   Registers all <work-*> elements from one import. Generated by tools/build.js — do not edit. */`;

  const result = await build({
    entryPoints: [join(SRC, "index.js")],
    outfile: join(DIST, "workponents.js"),
    bundle: true,
    format: "esm",
    platform: "browser",
    target: ["es2022"],
    minify: false,        // buildless-friendly: readable, debuggable
    sourcemap: false,
    legalComments: "none",
    banner: { js: banner },
    // The engine tiers import() their CDN specifiers via runtime *_CDN consts
    // (variable specifiers), so esbuild never tries to resolve/bundle them — they
    // stay lazy. We do NOT mark esm.sh as external (there are no static esm.sh
    // imports to mark); the variable-specifier dynamic import is inherently left
    // as a runtime import(). Lit + lit/directives/* resolve from node_modules and
    // ARE bundled (self-contained file).
    logLevel: "info",
    metafile: true,
  });

  // theme tokens → dist/theme.css (the package's ./theme.css export points here for
  // the dist consumer; src/theme/tokens.css remains the source of truth).
  cpSync(join(SRC, "theme", "tokens.css"), join(DIST, "theme.css"));

  // report
  const out = result.metafile.outputs[Object.keys(result.metafile.outputs)[0]];
  const kb = (out ? out.bytes : readFileSync(join(DIST, "workponents.js")).length) / 1024;
  console.log(`\n  dist/workponents.js  ${kb.toFixed(0)} KB  (Lit bundled · CDN engines stay lazy)`);
  console.log(`  dist/theme.css       ${(readFileSync(join(DIST, "theme.css")).length / 1024).toFixed(1)} KB`);

  if (!existsSync(join(DIST, "workponents.js"))) {
    console.error("build produced no dist/workponents.js");
    process.exit(1);
  }
}

main().catch((e) => {
  if (String(e).includes("Cannot find package 'esbuild'") || (e && e.code === "ERR_MODULE_NOT_FOUND")) {
    console.error(
      "build needs esbuild. The worktree symlinks ./node_modules → desktop/node_modules;\n" +
      "ensure that link exists, or run:  bun add -d esbuild   (in desktop/)",
    );
  } else {
    console.error(e);
  }
  process.exit(1);
});
