#!/bin/sh
exec /opt/homebrew/opt/llvm/bin/clang \
  --target=wasm32-wasip1 \
  --sysroot=/tmp/wasix-eh/wasix-sysroot-eh/sysroot \
  -resource-dir=/tmp/wasix-eh-rd \
  -D_GNU_SOURCE -D_WASI_EMULATED_PROCESS_CLOCKS -D_WASI_EMULATED_GETPID -D_WASI_EMULATED_MMAN \
  -matomics -mbulk-memory -mmutable-globals -mexception-handling -pthread \
  -Wno-implicit-function-declaration -Wno-int-conversion \
  "$@" \
  -lwasi-emulated-process-clocks -lwasi-emulated-getpid -lwasi-emulated-mman \
  -Wl,--shared-memory,--max-memory=4294967296
