#!/usr/bin/env node
/**
 * build-packs.mjs — regenerate packs/*.json AND the committed src/index.js
 * (data prologue + src/cli.js appended). Run it when the icon sources move:
 *
 *   node scripts/build-packs.mjs
 *
 * Sources (local-first, network fallback):
 *   material — material-icon-theme (desktop/node_modules if present, else
 *              jsDelivr at the pinned version). Keep MIT_VERSION aligned with
 *              desktop/package.json. folderNamesExpanded is NOT vendored: it
 *              is 100% derivable as `<closed>-open` (verified at build time).
 *   lobe     — @lobehub/icons-static-svg file listing (jsDelivr data API);
 *              the same filenames the raw.githubusercontent URLs serve.
 *   emoji    — github/gemoji db (alias → char), compact map.
 */
import fs from "node:fs";
import path from "node:path";

const here = path.dirname(new URL(import.meta.url).pathname);
const root = path.join(here, "..");

/** Pinned material-icon-theme version — keep aligned with desktop/package.json. */
const MIT_VERSION = "5.35.0";

async function getJson(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${url} → ${r.status}`);
  return r.json();
}

async function buildMaterial() {
  // Local-first: the desktop app vendors the same package via npm.
  const local = [
    path.join(root, "../../desktop/node_modules/material-icon-theme"),
    path.join(root, "../../../../desktop/node_modules/material-icon-theme"), // from a worktree
  ].find((p) => fs.existsSync(p));

  let manifest, defs;
  if (local) {
    manifest = JSON.parse(
      fs.readFileSync(path.join(local, "dist/material-icons.json"), "utf8"),
    );
    defs = fs
      .readdirSync(path.join(local, "icons"))
      .filter((f) => f.endsWith(".svg"))
      .map((f) => f.slice(0, -4));
  } else {
    manifest = await getJson(
      `https://cdn.jsdelivr.net/npm/material-icon-theme@${MIT_VERSION}/dist/material-icons.json`,
    );
    const flat = await getJson(
      `https://data.jsdelivr.com/v1/packages/npm/material-icon-theme@${MIT_VERSION}?structure=flat`,
    );
    defs = flat.files
      .map((f) => f.name)
      .filter((n) => n.startsWith("/icons/") && n.endsWith(".svg"))
      .map((n) => n.slice("/icons/".length, -".svg".length));
  }

  // Drop folderNamesExpanded only if it is fully derivable (closed + "-open").
  const underivable = Object.entries(manifest.folderNamesExpanded || {}).filter(
    ([k, v]) => v !== `${manifest.folderNames[k]}-open`,
  );
  if (underivable.length > 0)
    throw new Error(
      `folderNamesExpanded no longer derivable (${underivable.length} entries, e.g. ${underivable[0]}) — vendor it again`,
    );

  return {
    version: MIT_VERSION,
    file: manifest.file,
    folder: manifest.folder,
    folderExpanded: manifest.folderExpanded,
    fileNames: manifest.fileNames,
    fileExtensions: manifest.fileExtensions,
    folderNames: manifest.folderNames,
    defs: defs.sort(),
  };
}

async function buildLobe() {
  const resolved = await getJson(
    "https://data.jsdelivr.com/v1/packages/npm/@lobehub/icons-static-svg/resolved",
  );
  const flat = await getJson(
    `https://data.jsdelivr.com/v1/packages/npm/@lobehub/icons-static-svg@${resolved.version}?structure=flat`,
  );
  const slugs = flat.files
    .map((f) => f.name)
    .filter((n) => n.startsWith("/icons/") && n.endsWith(".svg"))
    .map((n) => n.slice("/icons/".length, -".svg".length))
    .sort();
  return { version: resolved.version, slugs };
}

async function buildEmoji() {
  const db = await getJson(
    "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json",
  );
  const names = {};
  for (const e of db) for (const a of e.aliases) names[a] = e.emoji;
  return names;
}

const [material, lobe, emoji] = await Promise.all([
  buildMaterial(),
  buildLobe(),
  buildEmoji(),
]);

const packs = { material, lobe, emoji };
for (const [name, data] of Object.entries(packs)) {
  fs.writeFileSync(
    path.join(root, "packs", `${name}.json`),
    JSON.stringify(data) + "\n",
  );
}

// src/index.js = data prologue + the handwritten CLI. The QuickJS wasm lane
// compiles ONE file with no module resolution, so the packs ride inline.
const cli = fs.readFileSync(path.join(root, "src/cli.js"), "utf8");
const banner =
  "// GENERATED by scripts/build-packs.mjs — DO NOT EDIT.\n" +
  "// Logic lives in src/cli.js; data in packs/*.json. Regenerate with:\n" +
  "//   node scripts/build-packs.mjs\n";
fs.writeFileSync(
  path.join(root, "src/index.js"),
  `${banner}globalThis.__ICONS_PACKS = ${JSON.stringify(packs)};\n${cli}`,
);

console.log(
  `packs written: material@${material.version} (${material.defs.length} defs, ` +
    `${Object.keys(material.fileNames).length} fileNames, ${Object.keys(material.fileExtensions).length} exts, ` +
    `${Object.keys(material.folderNames).length} folderNames) · lobe@${lobe.version} (${lobe.slugs.length} slugs) · ` +
    `emoji (${Object.keys(emoji).length} names) → src/index.js ${fs.statSync(path.join(root, "src/index.js")).size} bytes`,
);
