// Curated icon map for agent :ICON: values.
//
// Extracted so AgentIcon (renderer) and AgentIconPicker (search +
// picker grid) share a single source of truth. New icons land here;
// nothing else needs to be touched.
//
// Each value is a Svelte component from phosphor-svelte. The key is
// the PascalCase name agent authors reference via lucide:<Name> — the
// prefix and key set predate the Phosphor migration and stay stable
// for backward compatibility with icons persisted on disk; old Lucide
// names are aliased to their closest Phosphor equivalents.

import {
  Acorn,
  Binoculars,
  Bird,
  BookOpen,
  BookmarkSimple,
  Brain,
  Broadcast,
  Cat,
  ChatCircle,
  Code,
  Compass,
  Cpu,
  Crown,
  Dog,
  Eye,
  Feather,
  FileText,
  Fish,
  Flag,
  Funnel,
  Gauge,
  Ghost,
  Globe,
  GraduationCap,
  Hammer,
  Hash,
  Heart,
  Image,
  Key,
  Leaf,
  Lightbulb,
  Lightning,
  MagicWand,
  MagnifyingGlass,
  MapTrifold,
  Microphone,
  MusicNotes,
  Newspaper,
  PenNib,
  Plant,
  PushPin,
  PuzzlePiece,
  Rabbit,
  Robot,
  Rocket,
  Shapes,
  Shield,
  Shrimp,
  Sigma,
  Smiley,
  Sparkle,
  Stack,
  Star,
  Sun,
  Tag,
  Target,
  Terminal,
  Toolbox,
  TreeStructure,
  Trophy,
  Umbrella,
  VideoCamera,
  Wallet,
  Wrench,
} from "phosphor-svelte";

type IconComponent = typeof Star;

export const LUCIDE_MAP: Record<string, IconComponent> = {
  Anvil: Toolbox,
  Bird,
  BookOpen,
  Bookmark: BookmarkSimple,
  Bot: Robot,
  Brain,
  Cat,
  Code2: Code,
  Compass,
  Cpu,
  Crown,
  Dog,
  Eye,
  Feather,
  FileText,
  Filter: Funnel,
  Fish,
  Flag,
  Gauge,
  Ghost,
  Globe,
  GraduationCap,
  Hammer,
  Hash,
  Heart,
  Image,
  Key,
  Layers: Stack,
  Leaf,
  Lightbulb,
  Map: MapTrifold,
  MessageCircle: ChatCircle,
  Mic: Microphone,
  Music: MusicNotes,
  Newspaper,
  PenTool: PenNib,
  Pin: PushPin,
  Puzzle: PuzzlePiece,
  Rabbit,
  Radar: Broadcast,
  Rocket,
  Search: MagnifyingGlass,
  Shapes,
  Shield,
  Sigma,
  Smile: Smiley,
  Sparkle,
  Sparkles: Sparkle,
  Sprout: Plant,
  Squirrel: Acorn,
  Star,
  Sun,
  Tag,
  Target,
  Telescope: Binoculars,
  Terminal,
  Trophy,
  Turtle: Shrimp,
  Umbrella,
  Video: VideoCamera,
  Wallet,
  Wand2: MagicWand,
  Workflow: TreeStructure,
  Wrench,
  Zap: Lightning,
};

export const LUCIDE_NAMES: string[] = Object.keys(LUCIDE_MAP).sort();
