#!/usr/bin/env bash
# Build the in-sandbox JS toolchain (wb-fm0.4): QuickJS-ng compiled to wasm objects via
# clang.wasm + the work harness (Javy.IO + console + TextEncoder/Decoder). These objects are the
# "libquickjs" the per-program JS lane links against (Workbooks.Compilers.js_compile_to_wasm):
# JS source -> js_src.c (embedded) -> clang.wasm -> wasm-ld(harness + js_src + libquickjs).
# Untrusted JS thus compiles AND runs ENTIRELY in the sandbox (QuickJS interpreter, no JIT, no
# native javy). Idempotent: skips objects that already exist. Last stdout line = the obj dir.
set -euo pipefail
SD="$(cd "$(dirname "$0")" && pwd)"            # compilers/js
COMPILERS="$(cd "$SD/.." && pwd)"
CLANG="${CLANG:-$COMPILERS/clang/clang-root/llvm.core.wasm}"
CSYS="${CSYS:-$COMPILERS/clang/clang-root/sysroot}"
QJS_REF="${QJS_REF:-v0.10.0}"
QROOT="$SD/qjs-root"; QSRC="$QROOT/quickjs-ng"

exec 3>&1 1>&2
[ -f "$CLANG" ] || { echo "[js] clang.wasm missing — run ../clang/build.sh"; exit 1; }

mkdir -p "$QROOT"
[ -d "$QSRC" ] || { echo "[js] clone quickjs-ng $QJS_REF"; git clone --depth 1 -b "$QJS_REF" https://github.com/quickjs-ng/quickjs "$QSRC"; }

CL(){ wasmtime run -W exceptions=y --dir "$CSYS::/usr" --dir "$1::/work" --dir "$1::/tmp" \
      --env TMPDIR=/tmp "$CLANG" clang --target=wasm32-wasip1 --sysroot=/usr -O2 -w \
      -D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_PROCESS_CLOCKS "${@:2}"; }

# QuickJS core objects (the interpreter). xsum = quickjs-ng's extended-precision sum.
for f in quickjs cutils libregexp libunicode xsum; do
  if [ ! -f "$QSRC/$f.o" ]; then echo "[js] clang.wasm $f.c"; CL "$QSRC" -c "/work/$f.c" -o "/work/$f.o"; fi
done

# a wasm C unit (harness.c / harness_run.c) → .o, needing quickjs.h from QSRC.
cc_qjs(){ # $1 = basename (no .c)
  mkdir -p "$SD/.cc"; cp "$SD/$1.c" "$SD/.cc/$1.c"
  if [ ! -f "$SD/$1.o" ] || [ "$SD/$1.c" -nt "$SD/$1.o" ]; then
    echo "[js] clang.wasm $1.c"
    wasmtime run -W exceptions=y --dir "$CSYS::/usr" --dir "$SD/.cc::/work" --dir "$QSRC::/qjs" \
      --dir "$SD/.cc::/tmp" --env TMPDIR=/tmp "$CLANG" clang --target=wasm32-wasip1 --sysroot=/usr \
      -O2 -w -I/qjs -c "/work/$1.c" -o "/work/$1.o"
    cp "$SD/.cc/$1.o" "$SD/$1.o"
  fi
}

# (1) the per-program harness (harness.o) — only js_src.c varies per JS program.
cc_qjs harness

# (1b) the JsDock per-program harness (harness_dock.o, wb-e1x.1) — harness.o + env.* host-capability
#      imports (host_http_get / host_vfs_read|write) exposed to JS as Javy.Net / Javy.VFS. A command
#      linked against this runs under Workbooks.JsDock (Wasmex), never the bare wasmtime CLI.
cc_qjs harness_dock

# (1c) Generate the Node-core shim header from compilers/js/node/*.js (conflict-free fan-out: each Node
#      core module is its own file; agents add node/NN_mod.js without touching harness_run.c). The files
#      are concatenated IN FILENAME ORDER (00_open … 99_require) and C-string-escaped into .cc/node_prelude.h,
#      which defines `static const char *NODE_PRELUDE`. harness_run.c #includes it. Touch harness_run.c when
#      the header changes so cc_qjs recompiles (it only checks the .c's own mtime).
gen_node_header(){
  mkdir -p "$SD/.cc"
  local out="$SD/.cc/node_prelude.h" tmp="$SD/.cc/node_prelude.h.tmp"
  {
    echo "/* GENERATED by build.sh from compilers/js/node/*.js — do not edit. */"
    echo "static const char *NODE_PRELUDE ="
    for f in "$SD"/node/*.js; do
      # escape backslash then doublequote, wrap each source line as a C string literal with a trailing \n
      sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/  "/' -e 's/$/\\n"/' "$f"
    done
    echo "  ;"
  } > "$tmp"
  if ! cmp -s "$tmp" "$out" 2>/dev/null; then mv -f "$tmp" "$out"; touch "$SD/harness_run.c"; echo "[js] regen node_prelude.h"; else rm -f "$tmp"; fi
}
gen_node_header

# (2) qjs-run.wasm — generic QuickJS that evals a JS file given at runtime; used to run the
#     TypeScript compiler in-sandbox for the TS lane (wb-fm0.6). Link it (it embeds no source).
cc_qjs harness_run
if [ ! -f "$SD/qjs-run.wasm" ] || [ "$SD/harness_run.o" -nt "$SD/qjs-run.wasm" ]; then
  echo "[js] wasm-ld qjs-run.wasm"
  wasmtime run -W exceptions=y --dir "$CSYS::/usr" --dir "$SD/.cc::/work" --dir "$QSRC::/qjs" --env TMPDIR=/tmp \
    "$CLANG" wasm-ld -m wasm32 -z stack-size=8388608 --stack-first -L/usr/lib/wasm32-unknown-wasip1 -L/usr/lib/wasm32-wasip1 \
    /usr/lib/wasm32-wasip1/crt1-command.o /work/harness_run.o \
    /qjs/quickjs.o /qjs/cutils.o /qjs/libregexp.o /qjs/libunicode.o /qjs/xsum.o \
    -lc /usr/lib/wasm32-unknown-wasip1/libclang_rt.builtins.a -o /work/qjs-run.wasm
  cp "$SD/.cc/qjs-run.wasm" "$SD/qjs-run.wasm"
fi

# (3) the TypeScript transpiler job (wb-fm0.6): fetch typescript.js (single-file compiler),
#     assemble tsjob.js = node-shim preamble + typescript.js + transpile driver. Run in-sandbox
#     by qjs-run.wasm: TS on stdin → JS on stdout (ts.transpileModule, types stripped).
TS_VER="${TS_VER:-5.6.3}"
[ -f "$SD/ts/typescript.js" ] || { echo "[js] fetch typescript@$TS_VER";
  curl -fsSL "https://unpkg.com/typescript@$TS_VER/lib/typescript.js" -o "$SD/ts/typescript.js"; }
if [ ! -f "$SD/ts/tsjob.js" ] || [ "$SD/ts/preamble.js" -nt "$SD/ts/tsjob.js" ] || [ "$SD/ts/transpile.js" -nt "$SD/ts/tsjob.js" ]; then
  echo "[js] assemble ts/tsjob.js"
  cat "$SD/ts/preamble.js" "$SD/ts/typescript.js" "$SD/ts/transpile.js" > "$SD/ts/tsjob.js"
fi

echo "[js] DONE — libquickjs objects + harness.o + qjs-run.wasm + ts/tsjob.js"
echo "$QSRC" 1>&3
