// bit.ml's inline brand registry, SOURCED FROM THE GLYPHS TOOLKIT. brandify
// renders synchronously, so we resolve each brand once at build time (glyphs
// curated → svgl/simple-icons/lobehub CDN) and inline the SVG. Re-run to add
// brands. Source of truth: toolkits/glyphs.
import { glyphAsync } from '../../../../toolkits/glyphs/dist/glyphs.js';
import { writeFileSync } from 'node:fs';

// key → { name (display), match: [aliases the scanner looks for] }. Full-color
// where glyphs has it; AI/dev brands the demo content names.
const WANT = {
  google:['Google'], nvidia:['Nvidia','NVIDIA'], anthropic:['Anthropic'],
  claude:['Claude Code','Claude'], openai:['OpenAI'], codex:['Codex'],
  deepmind:['DeepMind'], gemini:['Gemini'], cursor:['Cursor'],
  githubcopilot:['GitHub Copilot','Copilot'], perplexity:['Perplexity'],
  huggingface:['Hugging Face','HuggingFace'], mistralai:['Mistral'],
  meta:['Meta'], microsoft:['Microsoft'], amazon:['Amazon','AWS'],
  apple:['Apple'], intel:['Intel'], amd:['AMD'], cloudflare:['Cloudflare'],
  github:['GitHub'], vercel:['Vercel'], replit:['Replit'], stripe:['Stripe'],
  x:['Grok'], notion:['Notion'], figma:['Figma'],
};
// some keys differ from the glyphs id; map to what glyphs resolves
const GID = { claude:'claude', codex:'openai', githubcopilot:'githubcopilot', x:'x', mistralai:'mistral' };

const out = {};
for (const [key, match] of Object.entries(WANT)) {
  const id = GID[key] || key;
  let svg = null;
  try { svg = await glyphAsync(`brand:${id}`, { size: '1em' }); } catch {}
  if (!svg) { try { svg = await glyphAsync(`icon:${id}`, { size: '1em' }); } catch {} }
  out[key] = { name: match[0], match, svg: svg || null };
  console.log(`${svg ? 'OK ' : '—  '} ${key} (${match.join(', ')})`);
}
const body = `// GENERATED by scripts/build-brands.mjs from the glyphs toolkit. Do not edit by hand.
export const BRAND_DATA = ${JSON.stringify(out, null, 2)};
`;
writeFileSync('src/lib/brand-data.js', body);
console.log(`\nwrote ${Object.keys(out).length} brands (${Object.values(out).filter(b=>b.svg).length} with marks)`);
