// GENERATED from sim/namegen.lua — do not edit by hand.
pub struct Bank { pub noun:&'static[&'static str], pub adj:&'static[&'static str], pub stem:&'static[&'static str], pub syll:&'static[&'static str], pub product:&'static[&'static str] }

pub fn bank(v:&str)->&'static Bank { match v {
  "skincare" => &Bank{ noun:&["Glow", "Dew", "Petal", "Bare", "Mist", "Balm", "Fern", "Tonic", "Rinse", "Velvet", "Clover", "Moss", "Pearl", "Sage", "Bloom", "Halo"], adj:&["Tidy", "Plain", "Gentle", "Quiet", "Honest", "Soft"], stem:&["lu", "ve", "se", "no", "ami", "cla", "do", "mi"], syll:&["mi", "na", "ra", "lia", "ve", "ne", "so", "del"], product:&["Cleanser", "Serum", "Balm", "Mist", "Cream", "Oil"] },
  "cookware" => &Bank{ noun:&["Hearth", "Ember", "Copper", "Whisk", "Rind", "Simmer", "Cast", "Grain", "Skillet", "Flame", "Crock", "Ladle", "Hew", "Char", "Salt", "Smoke"], adj:&["Plain", "Stout", "Honest", "Rustic", "True", "Iron"], stem:&["ca", "fer", "bra", "sto", "he", "ro", "gri", "ma"], syll:&["den", "ver", "lo", "na", "mer", "tan", "do", "sel"], product:&["Skillet", "Dutch Oven", "Saucier", "Stockpot", "Griddle", "Knife"] },
  "software" => &Bank{ noun:&["Ledger", "Beacon", "Stack", "Pilot", "Relay", "Plot", "Kit", "Draft", "Signal", "Anchor", "Cursor", "Branch", "Module", "Patch", "Query", "Scope"], adj:&["Plain", "Swift", "Tidy", "Open", "Bright", "Clear"], stem:&["ze", "vo", "qua", "ny", "lo", "dex", "fi", "su"], syll:&["dex", "bit", "ron", "ly", "go", "max", "ner", "tek"], product:&["App", "Pro Plan", "Suite", "Dashboard", "API", "Toolkit"] },
  "apparel" => &Bank{ noun:&["Loom", "Hem", "Weft", "Marlow", "Selvage", "Oak", "Harbor", "Twill", "Drift", "Field", "Cedar", "Wool", "Cuff", "Stitch", "Cove", "North"], adj:&["Plain", "True", "Worn", "Honest", "Quiet", "Sturdy"], stem:&["ma", "har", "we", "co", "fel", "bro", "li", "tra"], syll:&["low", "den", "ber", "ton", "ner", "field", "by", "rell"], product:&["Tee", "Jacket", "Chore Coat", "Henley", "Cap", "Sock"] },
  "beverages" => &Bank{ noun:&["Fizz", "Brew", "Spritz", "Pour", "Steep", "Zest", "Bramble", "Quench", "Cask", "Vine", "Hops", "Bubble", "Splash", "Grove", "Orchard", "Cellar"], adj:&["Crisp", "Cold", "Bright", "Wild", "Bold", "Pure"], stem:&["fiz", "spri", "bra", "ze", "ca", "vi", "ne", "lo"], syll:&["zo", "ber", "na", "ly", "co", "de", "sa", "vy"], product:&["Seltzer", "Kombucha", "Cold Brew", "Soda", "Cider", "Tonic"] },
  "beauty" => &Bank{ noun:&["Blush", "Tint", "Gloss", "Matte", "Kohl", "Lash", "Pout", "Flush", "Rouge", "Sheen", "Glaze", "Shade", "Bronze", "Veil", "Satin", "Dab"], adj:&["Dewy", "Bold", "Lush", "Vivid", "Soft", "Bare"], stem:&["bel", "lu", "ros", "gla", "vi", "mi", "se", "ka"], syll:&["lia", "na", "ra", "vie", "la", "mi", "sa", "ela"], product:&["Lipstick", "Mascara", "Foundation", "Blush", "Palette", "Concealer"] },
  "wellness" => &Bank{ noun:&["Vital", "Verve", "Vigor", "Restore", "Balance", "Flow", "Pulse", "Nourish", "Revive", "Renew", "Source", "Root", "Prime", "Spring", "Zenith", "Sustain"], adj:&["Daily", "Pure", "Whole", "Clean", "Calm", "Clear"], stem:&["vi", "na", "re", "zo", "bi", "so", "pra", "my"], syll:&["ta", "va", "lo", "sen", "da", "ne", "sa", "len"], product:&["Capsule", "Powder", "Gummy", "Tincture", "Blend", "Multi"] },
  "home" => &Bank{ noun:&["Nest", "Hollow", "Abode", "Vessel", "Nook", "Haven", "Roost", "Clay", "Slate", "Terra", "Hue", "Birch", "Ash", "Willow", "Alcove", "Bough"], adj:&["Cozy", "Warm", "Snug", "Plain", "Quiet", "Homespun"], stem:&["ho", "ne", "te", "ab", "ro", "cla", "wi", "ha"], syll:&["llow", "ven", "stead", "mere", "wood", "by", "den", "sa"], product:&["Throw", "Vase", "Candle", "Lamp", "Rug", "Planter"] },
  "pet" => &Bank{ noun:&["Paw", "Trot", "Romp", "Pounce", "Snout", "Whisker", "Tail", "Kibble", "Den", "Pack", "Howl", "Purr", "Nuzzle", "Scout", "Burrow", "Biscuit"], adj:&["Good", "Happy", "Loyal", "Scruffy", "Furry", "Frisky"], stem:&["pa", "fe", "ro", "po", "whi", "ta", "ki", "nu"], syll:&["ws", "sper", "ble", "per", "by", "kin", "do", "ly"], product:&["Treat", "Chew", "Leash", "Collar", "Bed", "Toy"] },
  "snacks" => &Bank{ noun:&["Crunch", "Munch", "Snap", "Nibble", "Crumb", "Bite", "Pop", "Cluster", "Batch", "Morsel", "Crackle", "Chomp", "Brittle", "Nugget", "Toasty", "Drizzle"], adj:&["Crispy", "Salty", "Sweet", "Tangy", "Toasted", "Bold"], stem:&["cru", "mu", "na", "po", "cri", "ba", "sni", "to"], syll:&["nch", "mble", "sa", "by", "kle", "la", "ster", "zo"], product:&["Bar", "Bites", "Chips", "Crackers", "Granola", "Cookie"] },
  _ => bank("cookware") }
}
pub static ABSTRACT:&[&str] = &["Theory", "Studio", "Lab", "Works", "Club", "House", "Method", "Index"];
pub static FORM:&[&str] = &["Co.", "Goods", "Supply", "Society", "Bros.", "& Sons"];
pub static TRAITS:&[&str] = &["thrifty", "loud", "heritage", "clinical", "playful", "earnest", "premium", "scrappy", "cozy", "bold", "nerdy", "breezy"];
pub static BLOCKLIST:&[&str] = &["nike", "apple", "glossier", "lodge", "patagonia", "adobe", "dove", "olay"];
