package workbooks:engine;

world engine {
  import session-info: func() -> string;
  import browse-fetch: func(url: string) -> string;
  import llm-complete: func(prompt: string) -> string;
  import run-command-many: func(command: string, inputs: string) -> string;
  import run-command: func(command: string, input: string, args: list<string>) -> string;
  import vfs-query: func(sql: string) -> string;
  export run: func(input: string) -> string;
}
