// Build-time inlined template strings for brand-book .org documents.
//
// Templates use a Mustache subset implemented in render.ts:
//   {{var}}               — scalar interpolation
//   {{#section}}…{{/section}} — truthy / array iteration
//   {{^section}}…{{/section}} — falsy / empty-array block
//   {{.}}                 — current item in an array (scalar items)
//
// Inlined here as TS string constants so the Cloudflare Worker has no
// file-read dependency at runtime. The .org.template files are the
// canonical source of truth; this file is generated by keeping them in
// sync (or just copied — they are small).

export const BRAND_TEMPLATE = `#+TITLE: {{brand_name}} brand book
#+GENERATED_AT: {{utc_iso}}
#+GENERATED_BY: brandnana v{{version}}
#+DOMAIN: {{domain}}
#+SLUG: {{slug}}

* {{brand_name}}                                                       :brand:
  :PROPERTIES:
  :ID:           {{slug}}
  :DOMAIN:       {{domain}}
  :LEGAL_NAME:   {{legal_name}}
  :FOUNDED:      {{founded_year}}
  :HQ:           {{hq_city}}
  :CATEGORY:     {{category}}
  :TAGLINE:      {{tagline}}
  :END:

** Descriptors
{{#descriptors}}
   - {{.}}
{{/descriptors}}

** Voice
{{voice_notes}}

** Visual identity                                                     :visual:

*** Primary palette                                                    :palette:primary:
    :PROPERTIES:
    :PRIMARY_HEX:    {{primary_hex}}
    :PRIMARY_NAME:   {{primary_name}}
    :SECONDARY_HEX:  {{secondary_hex}}
    :SECONDARY_NAME: {{secondary_name}}
    :END:

*** Extended palette                                                   :palette:extended:
    {{#extended_colors}}
    - {{name}}: {{hex}}
    {{/extended_colors}}

*** Typography                                                         :fonts:
    :PROPERTIES:
    :PRIMARY_FONT:   {{primary_font}}
    :SECONDARY_FONT: {{secondary_font}}
    :MONO_FONT:      {{mono_font}}
    :END:

*** Logo                                                               :logo:
    :PROPERTIES:
    :PRIMARY_URL:  {{logo_primary_url}}
    :ON_LIGHT_URL: {{logo_on_light_url}}
    :ON_DARK_URL:  {{logo_on_dark_url}}
    :SVG_PATH:     {{logo_svg_path}}
    :END:

** Social handles                                                      :social:
{{#social}}
   - {{network}}: {{handle}} ({{url}})
{{/social}}

** Captured by
{{#capture_verbs}}
   - {{verb}}@{{ts}}: {{summary}}
{{/capture_verbs}}
`;

export const COMPETITOR_TEMPLATE = `#+TITLE: {{competitor_name}} — competitor of {{brand_name}}
#+GENERATED_AT: {{utc_iso}}

* {{competitor_name}}                                          :competitor:
  :PROPERTIES:
  :ID:        {{slug}}
  :DOMAIN:    {{domain}}
  :CATEGORY:  {{category}}
  :END:

** Snapshot
   {{snapshot_notes}}

** Visual deltas vs {{brand_name}}                             :delta:
   :PROPERTIES:
   :PALETTE_DISTANCE: {{palette_distance}}
   :TONE_DELTA:       {{tone_delta}}
   :END:

   {{delta_notes}}

** Ads                                                         :ads:
{{#ads}}
*** {{ad_headline}}                                            :ad:
    :PROPERTIES:
    :AD_ID:        {{ad_id}}
    :PROVIDER:     {{provider}}
    :FIRST_SEEN:   {{first_seen}}
    :LAST_SEEN:    {{last_seen}}
    :PLATFORM:     {{platform}}
    :CTA:          {{cta}}
    :LANDING_URL:  {{landing_url}}
    :MEDIA_URL:    {{media_url}}
    :MEDIA_TYPE:   {{media_type}}
    :END:

    {{ad_body}}

    Analysis:
    - Theme:   {{theme}}
    - Emotion: {{emotion}}
    - Hook:    {{hook}}
{{/ads}}
`;

export const PRODUCTS_TEMPLATE = `#+TITLE: {{brand_name}} product catalog
#+GENERATED_AT: {{utc_iso}}
#+PRODUCT_COUNT: {{product_count}}
#+CATEGORY_COUNT: {{category_count}}

* Catalog

** by-category                                                 :index:category:
{{#categories}}
*** {{name}}
{{#subcategories}}
**** {{name}}
{{#products}}
***** {{name}}                                                 :product:
      :PROPERTIES:
      :ID:         {{slug}}
      :SKU:        {{sku}}
      :PRICE:      {{price}}
      :CURRENCY:   {{currency}}
      :SIZES:      {{sizes_csv}}
      :COLORS:     {{colors_csv}}
      :IMAGES:     {{images_csv}}
      :URL:        {{url}}
      :STOCK:      {{stock_status}}
      :MATERIALS:  {{materials_csv}}
      :TAGS:       {{tags_csv}}
      :CATEGORY:   {{category_path}}
      :COLLECTION: {{collection}}
      :PRICE_BAND: {{price_band}}
      :END:

      {{description}}
{{/products}}
{{/subcategories}}
{{/categories}}

** by-collection                                               :index:collection:
{{#collections}}
*** {{name}}
{{#products}}
**** {{name}} ([[id:{{slug}}][see canonical]])               :product:ref:
{{/products}}
{{/collections}}

** by-color                                                    :index:color:
{{#colors}}
*** {{name}}                                                   :color:{{slug}}:
{{#products}}
**** {{name}} ([[id:{{slug}}][see canonical]])               :product:ref:
{{/products}}
{{/colors}}

** by-price-band                                               :index:price-band:
{{#price_bands}}
*** {{name}}
{{#products}}
**** {{name}} — \${{price}} ([[id:{{slug}}][see canonical]]) :product:ref:
{{/products}}
{{/price_bands}}

** by-stock-status                                             :index:stock-status:
{{#stock_groups}}
*** {{status}}
{{#products}}
**** {{name}} ([[id:{{slug}}][see canonical]])               :product:ref:
{{/products}}
{{/stock_groups}}
`;

export const TIMELINE_TEMPLATE = `#+TITLE: {{brand_name}} brand-book capture timeline
#+GENERATED_AT: {{utc_iso}}

* Capture log
{{#events}}
** {{ts}} — {{verb_id}}                                        :event:{{status}}:
   :PROPERTIES:
   :VERB:           {{verb_id}}
   :STATUS:         {{status}}
   :DURATION_MS:    {{duration_ms}}
   :VENDOR_COST:    \${{vendor_cost_usd}}
   :CUSTOMER_CHARGE: \${{customer_charge_usd}}
   :MARGIN:         \${{margin_usd}}
   :END:

   {{summary}}

{{#error}}
   ERROR: {{error}}
{{/error}}
{{/events}}
`;
